// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lan_lock`, `rejected_lock`, `sanitize`, `share_with_peer`, `sync_lock`, `with_sync`, `with_vault`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`, `from`

/// Sets the language of core error messages (`"ko"`, `"en"`, or a locale like `"ko-KR"`).
///
/// An unknown value falls back to the system locale. Call it once before the other APIs,
/// and again whenever the language changes, or the screen ends up mixing languages.
Future<void> setLanguage({required String code}) =>
    RustLib.instance.api.crateApiSetLanguage(code: code);

/// Language code currently used for core messages.
Future<String> language() => RustLib.instance.api.crateApiLanguage();

/// Collects the mobile strings for the current language.
Future<FfiStrings> mobileStrings() =>
    RustLib.instance.api.crateApiMobileStrings();

/// Opens the vault, creating it if needed. `vault_dir` is the synced directory,
/// `cache_db_path` the device-local SQLite file.
Future<void> vaultOpen(
        {required String vaultDir,
        required String cacheDbPath,
        required String password}) =>
    RustLib.instance.api.crateApiVaultOpen(
        vaultDir: vaultDir, cacheDbPath: cacheDbPath, password: password);

/// Closes the vault (log out).
Future<void> vaultClose() => RustLib.instance.api.crateApiVaultClose();

/// Whether `vault_dir` already holds a vault.
///
/// The lock screen asks before anything is unlocked, to tell "set a password" from "enter
/// the password" — and to know that the vault it just created is the one to show a recovery
/// code for.
Future<bool> vaultExists({required String vaultDir}) =>
    RustLib.instance.api.crateApiVaultExists(vaultDir: vaultDir);

/// Whether the vault at `vault_dir` has a recovery code, without opening it.
Future<bool> vaultHasRecoveryCode({required String vaultDir}) =>
    RustLib.instance.api.crateApiVaultHasRecoveryCode(vaultDir: vaultDir);

/// Replaces the master password of the open vault, after checking the current one.
Future<void> vaultChangePassword(
        {required String current, required String newPassword}) =>
    RustLib.instance.api.crateApiVaultChangePassword(
        current: current, newPassword: newPassword);

/// Issues a fresh recovery code, retiring any earlier one, and returns it.
///
/// **The only time the code is readable.** Only its Argon2id wrapper is stored, so a code
/// that is not written down is gone.
Future<String> vaultIssueRecoveryCode() =>
    RustLib.instance.api.crateApiVaultIssueRecoveryCode();

/// Sets a new master password from the recovery code, for a vault nobody can unlock.
///
/// Takes the directory rather than an open vault, because the whole point is that it cannot
/// be opened. Unlock with the new password afterwards; the recovery code stays valid.
Future<void> vaultResetPasswordWithRecovery(
        {required String vaultDir,
        required String code,
        required String newPassword}) =>
    RustLib.instance.api.crateApiVaultResetPasswordWithRecovery(
        vaultDir: vaultDir, code: code, newPassword: newPassword);

/// Deletes this device's vault and its cache: the way out of a forgotten password when there
/// is no recovery code either.
///
/// **Unsharing comes first and is not optional.** Syncthing propagates deletions, so emptying
/// a folder it still carries would delete the memos on every paired device too. If the folder
/// cannot be released, nothing is deleted at all. The daemon keeps running: it is still this
/// device's identity, and the vault created next registers a folder under the same id.
Future<void> vaultReset(
        {required String vaultDir, required String cacheDbPath}) =>
    RustLib.instance.api
        .crateApiVaultReset(vaultDir: vaultDir, cacheDbPath: cacheDbPath);

/// Memos, most recently updated first.
Future<List<FfiMemo>> memoList() => RustLib.instance.api.crateApiMemoList();

/// Creates (`id` = None) or updates (`id` = Some) a memo and returns its id.
Future<String> memoUpsert(
        {String? id, required String title, required String body}) =>
    RustLib.instance.api.crateApiMemoUpsert(id: id, title: title, body: body);

/// Deletes a memo.
Future<void> memoDelete({required String id}) =>
    RustLib.instance.api.crateApiMemoDelete(id: id);

/// Sets the palette key.
Future<void> memoSetColor({required String id, required String color}) =>
    RustLib.instance.api.crateApiMemoSetColor(id: id, color: color);

/// Sets the opacity in percent; the core clamps out-of-range values.
Future<void> memoSetOpacity(
        {required String id, required PlatformInt64 opacity}) =>
    RustLib.instance.api.crateApiMemoSetOpacity(id: id, opacity: opacity);

/// Moves a memo into a group; an empty `group_id` moves it to the top level.
Future<void> memoSetGroup({required String id, required String groupId}) =>
    RustLib.instance.api.crateApiMemoSetGroup(id: id, groupId: groupId);

/// Photos on one memo, in the order they were added.
Future<List<FfiAttachment>> attachmentList({required String memoId}) =>
    RustLib.instance.api.crateApiAttachmentList(memoId: memoId);

/// Attaches a photo; `data` is the original file bytes.
///
/// Dart decodes and passes `width_px`/`height_px`, so the core needs no image decoder. Pass
/// 0 when unknown and the aspect ratio falls back to 1:1.
Future<FfiAttachment> attachmentAdd(
        {required String memoId,
        required List<int> data,
        required String name,
        required String mime,
        required PlatformInt64 widthPx,
        required PlatformInt64 heightPx}) =>
    RustLib.instance.api.crateApiAttachmentAdd(
        memoId: memoId,
        data: data,
        name: name,
        mime: mime,
        widthPx: widthPx,
        heightPx: heightPx);

/// Photo bytes. Errors while the blob has not synced yet; draw a placeholder instead.
Future<Uint8List> attachmentBytes({required String hash}) =>
    RustLib.instance.api.crateApiAttachmentBytes(hash: hash);

/// Whether the photo has arrived on this device; do not ask for bytes if it has not.
Future<bool> attachmentHasBlob({required String hash}) =>
    RustLib.instance.api.crateApiAttachmentHasBlob(hash: hash);

/// Sets the display width in 1/1000 em; other devices see the same proportion.
Future<void> attachmentSetWidth(
        {required String id, required PlatformInt64 widthEmMilli}) =>
    RustLib.instance.api
        .crateApiAttachmentSetWidth(id: id, widthEmMilli: widthEmMilli);

/// Sets where the photo sits on the note and how wide it is, in one write.
///
/// The position is a fraction of the note (per-mille) rather than pixels, so a photo dropped
/// two thirds of the way down a phone screen is two thirds of the way down a desktop sticky
/// too. Both are clamped by the core.
Future<void> attachmentSetLayout(
        {required String id,
        required PlatformInt64 xPermille,
        required PlatformInt64 yPermille,
        required PlatformInt64 widthEmMilli}) =>
    RustLib.instance.api.crateApiAttachmentSetLayout(
        id: id,
        xPermille: xPermille,
        yPermille: yPermille,
        widthEmMilli: widthEmMilli);

/// Detaches a photo; the blob file stays (no GC).
Future<void> attachmentRemove({required String id}) =>
    RustLib.instance.api.crateApiAttachmentRemove(id: id);

/// All groups, sorted by name.
Future<List<FfiGroup>> groupList() => RustLib.instance.api.crateApiGroupList();

/// The folders directly inside `parent_id` (`""` for the top level), name-sorted.
///
/// The resolution is the core's, not Dart's, so the same defence applies on both platforms:
/// a group whose ancestry loops — which CRDTs allow, since a concurrent move on two devices
/// keeps both parents — or whose parent is gone surfaces at the top level instead of being
/// unreachable. Dart walking `parent_id` itself could loop forever on exactly that case.
Future<List<FfiGroup>> groupChildren({required String parentId}) =>
    RustLib.instance.api.crateApiGroupChildren(parentId: parentId);

/// The memos in one folder, newest first.
///
/// A memo whose group has been deleted elsewhere is shown at the **top level** rather than
/// nowhere, which is what the desktop list does too. Anything else would read as data loss.
Future<List<FfiMemo>> memosInGroup({required String groupId}) =>
    RustLib.instance.api.crateApiMemosInGroup(groupId: groupId);

/// Creates a group and returns its id.
Future<String> groupCreate({required String name, required String parentId}) =>
    RustLib.instance.api.crateApiGroupCreate(name: name, parentId: parentId);

/// Renames a group.
Future<void> groupRename({required String id, required String name}) =>
    RustLib.instance.api.crateApiGroupRename(id: id, name: name);

/// Sets a group's palette key. Folders carry a color just like memos and sync it the same
/// way, so the two UIs agree on what a folder looks like.
Future<void> groupSetColor({required String id, required String color}) =>
    RustLib.instance.api.crateApiGroupSetColor(id: id, color: color);

/// Moves a group under another; moving it into its own subtree is rejected.
Future<void> groupMove({required String id, required String parentId}) =>
    RustLib.instance.api.crateApiGroupMove(id: id, parentId: parentId);

/// Deletes a group; its memos and subgroups move up instead of being deleted.
Future<void> groupDelete({required String id}) =>
    RustLib.instance.api.crateApiGroupDelete(id: id);

/// Merges the other devices' logs into the local state; call it after the transport has
/// delivered new logs.
Future<void> syncRebuild() => RustLib.instance.api.crateApiSyncRebuild();

/// Starts the daemon and registers the vault directory, returning this device's pairing code.
///
/// Idempotent, which is what makes it safe to call on every resume. The first start generates
/// the device key and can take a few seconds; flutter_rust_bridge runs this off the UI thread
/// on its own.
Future<String> syncStart(
        {required String binaryPath,
        required String homeDir,
        required String vaultDir}) =>
    RustLib.instance.api.crateApiSyncStart(
        binaryPath: binaryPath, homeDir: homeDir, vaultDir: vaultDir);

/// Re-registers the vault directory with the running daemon.
///
/// [`sync_start`] does this on its first run and then short-circuits, so a vault created
/// after [`vault_reset`] — which removes the folder on purpose — would sit there unshared
/// until the app was next restarted. Doing nothing when the daemon is down is correct: the
/// next `sync_start` registers it anyway.
Future<void> syncEnsureFolder({required String vaultDir}) =>
    RustLib.instance.api.crateApiSyncEnsureFolder(vaultDir: vaultDir);

/// Stops the daemon. Safe to call when it is not running.
Future<void> syncStop() => RustLib.instance.api.crateApiSyncStop();

/// Whether the daemon is up. Cheap: it does not talk to it.
Future<bool> syncRunning() => RustLib.instance.api.crateApiSyncRunning();

/// This device's pairing code (`YMEMO1:<device-id>`), for the other device to scan or type.
Future<String> syncPairingCode() =>
    RustLib.instance.api.crateApiSyncPairingCode();

/// Pairs with a scanned or typed code: registers the peer and shares the vault with it.
///
/// Returns the peer's device id, which the screen then waits on: this side is now dialling a
/// device that has never heard of it, so nothing syncs until the **other** device allows the
/// request in (`sync_pending_devices` there). It no longer has to be given this device's code
/// by hand — that was the second scan nobody remembered to do.
Future<String> syncPairWith({required String code}) =>
    RustLib.instance.api.crateApiSyncPairWith(code: code);

/// Devices this vault is shared with, ourselves excluded.
Future<List<FfiSharedDevice>> syncDevices() =>
    RustLib.instance.api.crateApiSyncDevices();

/// Drops a peer. Only this side stops syncing; the other device keeps its own entry until it
/// unpairs too.
Future<void> syncUnpair({required String deviceId}) =>
    RustLib.instance.api.crateApiSyncUnpair(deviceId: deviceId);

/// Requests waiting for an answer, oldest first, minus the ones already rejected.
Future<List<FfiPendingDevice>> syncPendingDevices() =>
    RustLib.instance.api.crateApiSyncPendingDevices();

/// Allows a device in: shares the vault with it, completing the link.
///
/// Syncthing drops the pending entry as soon as the device is in the config, so there is
/// nothing to clear afterwards.
Future<void> syncApproveDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiSyncApproveDevice(deviceId: deviceId);

/// Turns a device away and stops asking about it for the rest of this run.
Future<void> syncRejectDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiSyncRejectDevice(deviceId: deviceId);

/// The verification code to show while waiting for `peer_device_id` to allow this device in.
///
/// The same eight characters the other side sees on its approval prompt, derived from the
/// two device ids alone.
Future<String> syncVerificationCode({required String peerDeviceId}) =>
    RustLib.instance.api
        .crateApiSyncVerificationCode(peerDeviceId: peerDeviceId);

/// Enters pairing mode and returns the code to show. Needs the daemon, since the code's whole
/// purpose is to hand over its device id.
Future<String> lanStart() => RustLib.instance.api.crateApiLanStart();

/// The code currently on offer. It rotates every minute, so the screen re-reads it.
Future<String?> lanCode() => RustLib.instance.api.crateApiLanCode();

/// Leaves pairing mode: the socket closes and the code stops being answered.
Future<void> lanStop() => RustLib.instance.api.crateApiLanStop();

/// Picks up devices that paired with **us** (they typed our code) and shares the vault with
/// each. Returns their ids, for the screen to report. Poll it while pairing mode is on.
Future<List<String>> lanPollPaired() =>
    RustLib.instance.api.crateApiLanPollPaired();

/// Pairs with the device showing `code`: broadcasts for it, and on an answer shares the vault
/// with it. `None` means nobody answered in time — a wrong or expired code, or a network that
/// drops broadcasts.
///
/// Blocks for up to `timeout_secs`; flutter_rust_bridge keeps that off the UI thread.
Future<String?> lanJoin({required String code, required BigInt timeoutSecs}) =>
    RustLib.instance.api.crateApiLanJoin(code: code, timeoutSecs: timeoutSecs);

/// Reads the settings; a missing or damaged file gives the defaults rather than an error,
/// since preferences must never be what stops the app from starting.
Future<FfiSettings> settingsLoad({required String path}) =>
    RustLib.instance.api.crateApiSettingsLoad(path: path);

/// Writes the settings back, sanitized. Returns the values as stored, so the screen can show
/// what was actually kept.
Future<FfiSettings> settingsSave(
        {required String path, required FfiSettings settings}) =>
    RustLib.instance.api.crateApiSettingsSave(path: path, settings: settings);

/// The open vault's key, for caching. Only meaningful right after an unlock.
Future<Uint8List> vaultKey() => RustLib.instance.api.crateApiVaultKey();

/// Reopens the vault with a cached key instead of the password.
///
/// This **skips the divergent-key healing** that `vault_open` does, because healing needs the
/// password to re-derive old keys. A vault that has diverged therefore fails here; the caller
/// is expected to drop the cached key and ask for the password, which is exactly what the
/// desktop does.
Future<void> vaultOpenWithKey(
        {required String vaultDir,
        required String cacheDbPath,
        required List<int> key}) =>
    RustLib.instance.api.crateApiVaultOpenWithKey(
        vaultDir: vaultDir, cacheDbPath: cacheDbPath, key: key);

/// The running build's version — the same number the release tag carries, since CI checks
/// the two against each other. Shown in settings, where it is what a bug report needs.
Future<String> appVersion() => RustLib.instance.api.crateApiAppVersion();

/// Asks GitHub whether there is a newer release. `None` means this build is current.
///
/// The **only** request the app makes to anyone's server, which is why it sits behind a
/// setting; see `ymemo_core::update` for what it does and does not send.
Future<FfiRelease?> updateCheck() => RustLib.instance.api.crateApiUpdateCheck();

/// A photo attachment as handed to Dart.
///
/// The bytes are not included: photos run to megabytes and carrying them in every list
/// would be waste. Fetch them by hash with [`attachment_bytes`] when drawing.
class FfiAttachment {
  final String id;
  final String memoId;
  final String hash;
  final String name;
  final String mime;

  /// Original pixel size for the aspect ratio; 0 when unknown.
  final PlatformInt64 widthPx;
  final PlatformInt64 heightPx;

  /// Display width in 1/1000 em; pixels = value / 1000 * the platform's base font px.
  final PlatformInt64 widthEmMilli;

  /// Top-left corner on the note, in per-mille of the note area (0..=1000 across and down).
  final PlatformInt64 xPermille;
  final PlatformInt64 yPermille;
  final PlatformInt64 createdAt;

  const FfiAttachment({
    required this.id,
    required this.memoId,
    required this.hash,
    required this.name,
    required this.mime,
    required this.widthPx,
    required this.heightPx,
    required this.widthEmMilli,
    required this.xPermille,
    required this.yPermille,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      memoId.hashCode ^
      hash.hashCode ^
      name.hashCode ^
      mime.hashCode ^
      widthPx.hashCode ^
      heightPx.hashCode ^
      widthEmMilli.hashCode ^
      xPermille.hashCode ^
      yPermille.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAttachment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          memoId == other.memoId &&
          hash == other.hash &&
          name == other.name &&
          mime == other.mime &&
          widthPx == other.widthPx &&
          heightPx == other.heightPx &&
          widthEmMilli == other.widthEmMilli &&
          xPermille == other.xPermille &&
          yPermille == other.yPermille &&
          createdAt == other.createdAt;
}

/// A group (folder) as handed to Dart.
class FfiGroup {
  final String id;
  final String name;
  final String parentId;

  /// Palette key, the same set memos use; the core never turns it into a real color.
  final String color;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const FfiGroup({
    required this.id,
    required this.name,
    required this.parentId,
    required this.color,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      color.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiGroup &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          color == other.color &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// A memo as handed to Dart; same fields as the core `Memo`.
class FfiMemo {
  final String id;
  final String title;
  final String body;
  final String color;
  final PlatformInt64 opacity;
  final String groupId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const FfiMemo({
    required this.id,
    required this.title,
    required this.body,
    required this.color,
    required this.opacity,
    required this.groupId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      body.hashCode ^
      color.hashCode ^
      opacity.hashCode ^
      groupId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiMemo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          body == other.body &&
          color == other.color &&
          opacity == other.opacity &&
          groupId == other.groupId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// A device asking to be let in.
class FfiPendingDevice {
  /// Syncthing device id; the handle for approving or rejecting.
  final String id;

  /// The name it announced. **It chose this itself**, so the UI must show it as a hint
  /// next to the id and never in place of one.
  final String name;

  /// The eight characters the other device is showing on its own screen right now. The
  /// user comparing the two is what makes an approval safe; see `ymemo_core::pairing`.
  final String verificationCode;

  const FfiPendingDevice({
    required this.id,
    required this.name,
    required this.verificationCode,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ verificationCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPendingDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          verificationCode == other.verificationCode;
}

/// A release newer than the running build.
class FfiRelease {
  final String version;

  /// Where the update button goes: the apk built for this device's ABI when the release
  /// carries one, the release page otherwise. The app opens it and installs nothing itself.
  final String url;

  /// File name behind [`FfiRelease::url`], empty when it is the release page. Shown so the
  /// user can see it is the apk for their phone and not one of the other two.
  final String file;

  const FfiRelease({
    required this.version,
    required this.url,
    required this.file,
  });

  @override
  int get hashCode => version.hashCode ^ url.hashCode ^ file.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiRelease &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          url == other.url &&
          file == other.file;
}

/// Preferences as Dart sees them. Every field has a default, so a file written by an older
/// version still loads.
class FfiSettings {
  /// `"auto"` (system locale), `"ko"` or `"en"`.
  final String lang;

  /// Days the vault reopens without the password after one unlock; 0 asks every time.
  final int unlockDays;

  /// Close the vault when the app leaves the foreground.
  final bool lockOnBackground;

  /// Ask GitHub about newer releases. The app's only outbound request.
  final bool updateCheck;

  /// When that last happened (epoch millis), so it is not asked on every start.
  final PlatformInt64 lastUpdateCheck;

  const FfiSettings({
    required this.lang,
    required this.unlockDays,
    required this.lockOnBackground,
    required this.updateCheck,
    required this.lastUpdateCheck,
  });

  static Future<FfiSettings> default_() =>
      RustLib.instance.api.crateApiFfiSettingsDefault();

  @override
  int get hashCode =>
      lang.hashCode ^
      unlockDays.hashCode ^
      lockOnBackground.hashCode ^
      updateCheck.hashCode ^
      lastUpdateCheck.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiSettings &&
          runtimeType == other.runtimeType &&
          lang == other.lang &&
          unlockDays == other.unlockDays &&
          lockOnBackground == other.lockOnBackground &&
          updateCheck == other.updateCheck &&
          lastUpdateCheck == other.lastUpdateCheck;
}

/// Another device sharing this vault.
class FfiSharedDevice {
  /// Syncthing device id — also what unpairing takes.
  final String id;

  /// Name the peer announced; empty when it has none.
  final String name;
  final bool connected;

  const FfiSharedDevice({
    required this.id,
    required this.name,
    required this.connected,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ connected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiSharedDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          connected == other.connected;
}

/// The mobile UI strings in the current language; Dart fetches these once at startup.
///
/// Keeping them in Dart instead would split the languages — catalog for core errors,
/// hardcoded for the screens. Reading the keys **in Rust** also puts mobile strings under
/// `ymemo-i18n`'s "every key used in code exists in the catalog" test. After
/// [`set_language`], fetch this again.
class FfiStrings {
  final String addPhoto;
  final String bodyHint;
  final String cameraError;
  final String connected;
  final String copied;
  final String copy;
  final String disconnected;
  final String lanConnect;
  final String lanDone;
  final String lanEnterCode;
  final String lanMyCode;
  final String lanNotFound;
  final String lanPairing;
  final String lanSearching;
  final String daysUnit;
  final String language;
  final String languageAuto;
  final String lockNow;
  final String lockOnBackground;
  final String lockOnBackgroundHint;
  final String lockSection;
  final String saved;
  final String settings;
  final String unlockDays;
  final String unlockDaysHint;
  final String updateAvailable;
  final String updateCheck;
  final String updateCheckHint;
  final String updateChecking;
  final String updateLatest;
  final String updateNow;
  final String updateOpen;
  final String updateSection;
  final String version;
  final String cancel;
  final String delete;
  final String deleteGroupHint;
  final String emptyFolder;
  final String folderName;
  final String moveTo;
  final String newGroup;
  final String ok;
  final String rename;
  final String rootFolder;
  final String listTitle;
  final String masterPassword;
  final String myCode;
  final String newMemo;
  final String noDevices;
  final String opening;
  final String photoCamera;
  final String photoGallery;
  final String photoMissing;
  final String photoRemove;
  final String photoSize;
  final String save;
  final String scanHint;
  final String scanQr;
  final String syncDevices;
  final String syncNow;
  final String syncStarting;
  final String syncUnavailable;
  final String titleHint;
  final String unlock;
  final String unpair;
  final String color;
  final String changePassword;
  final String confirmPassword;
  final String createVault;
  final String currentPassword;
  final String forgotPassword;
  final String issueRecovery;
  final String newPassword;
  final String newVaultHint;
  final String noRecovery;
  final String passwordChanged;
  final String passwordHint;
  final String passwordMismatch;
  final String recoveryAbsent;
  final String recoveryAck;
  final String recoveryCode;
  final String recoveryHint;
  final String recoveryIssued;
  final String recoveryPresent;
  final String recoveryPrompt;
  final String recoveryWarning;
  final String reissueRecovery;
  final String resetDone;
  final String resetPassword;
  final String resetVault;
  final String resetVaultConfirm;
  final String resetVaultHint;
  final String securitySection;
  final String allow;
  final String deviceId;
  final String pairCancelWait;
  final String pairConnected;
  final String pairRequest;
  final String pairRequestHint;
  final String pairVerification;
  final String pairVerify;
  final String pairWaiting;
  final String pairWaitingHint;
  final String reject;

  const FfiStrings({
    required this.addPhoto,
    required this.bodyHint,
    required this.cameraError,
    required this.connected,
    required this.copied,
    required this.copy,
    required this.disconnected,
    required this.lanConnect,
    required this.lanDone,
    required this.lanEnterCode,
    required this.lanMyCode,
    required this.lanNotFound,
    required this.lanPairing,
    required this.lanSearching,
    required this.daysUnit,
    required this.language,
    required this.languageAuto,
    required this.lockNow,
    required this.lockOnBackground,
    required this.lockOnBackgroundHint,
    required this.lockSection,
    required this.saved,
    required this.settings,
    required this.unlockDays,
    required this.unlockDaysHint,
    required this.updateAvailable,
    required this.updateCheck,
    required this.updateCheckHint,
    required this.updateChecking,
    required this.updateLatest,
    required this.updateNow,
    required this.updateOpen,
    required this.updateSection,
    required this.version,
    required this.cancel,
    required this.delete,
    required this.deleteGroupHint,
    required this.emptyFolder,
    required this.folderName,
    required this.moveTo,
    required this.newGroup,
    required this.ok,
    required this.rename,
    required this.rootFolder,
    required this.listTitle,
    required this.masterPassword,
    required this.myCode,
    required this.newMemo,
    required this.noDevices,
    required this.opening,
    required this.photoCamera,
    required this.photoGallery,
    required this.photoMissing,
    required this.photoRemove,
    required this.photoSize,
    required this.save,
    required this.scanHint,
    required this.scanQr,
    required this.syncDevices,
    required this.syncNow,
    required this.syncStarting,
    required this.syncUnavailable,
    required this.titleHint,
    required this.unlock,
    required this.unpair,
    required this.color,
    required this.changePassword,
    required this.confirmPassword,
    required this.createVault,
    required this.currentPassword,
    required this.forgotPassword,
    required this.issueRecovery,
    required this.newPassword,
    required this.newVaultHint,
    required this.noRecovery,
    required this.passwordChanged,
    required this.passwordHint,
    required this.passwordMismatch,
    required this.recoveryAbsent,
    required this.recoveryAck,
    required this.recoveryCode,
    required this.recoveryHint,
    required this.recoveryIssued,
    required this.recoveryPresent,
    required this.recoveryPrompt,
    required this.recoveryWarning,
    required this.reissueRecovery,
    required this.resetDone,
    required this.resetPassword,
    required this.resetVault,
    required this.resetVaultConfirm,
    required this.resetVaultHint,
    required this.securitySection,
    required this.allow,
    required this.deviceId,
    required this.pairCancelWait,
    required this.pairConnected,
    required this.pairRequest,
    required this.pairRequestHint,
    required this.pairVerification,
    required this.pairVerify,
    required this.pairWaiting,
    required this.pairWaitingHint,
    required this.reject,
  });

  @override
  int get hashCode =>
      addPhoto.hashCode ^
      bodyHint.hashCode ^
      cameraError.hashCode ^
      connected.hashCode ^
      copied.hashCode ^
      copy.hashCode ^
      disconnected.hashCode ^
      lanConnect.hashCode ^
      lanDone.hashCode ^
      lanEnterCode.hashCode ^
      lanMyCode.hashCode ^
      lanNotFound.hashCode ^
      lanPairing.hashCode ^
      lanSearching.hashCode ^
      daysUnit.hashCode ^
      language.hashCode ^
      languageAuto.hashCode ^
      lockNow.hashCode ^
      lockOnBackground.hashCode ^
      lockOnBackgroundHint.hashCode ^
      lockSection.hashCode ^
      saved.hashCode ^
      settings.hashCode ^
      unlockDays.hashCode ^
      unlockDaysHint.hashCode ^
      updateAvailable.hashCode ^
      updateCheck.hashCode ^
      updateCheckHint.hashCode ^
      updateChecking.hashCode ^
      updateLatest.hashCode ^
      updateNow.hashCode ^
      updateOpen.hashCode ^
      updateSection.hashCode ^
      version.hashCode ^
      cancel.hashCode ^
      delete.hashCode ^
      deleteGroupHint.hashCode ^
      emptyFolder.hashCode ^
      folderName.hashCode ^
      moveTo.hashCode ^
      newGroup.hashCode ^
      ok.hashCode ^
      rename.hashCode ^
      rootFolder.hashCode ^
      listTitle.hashCode ^
      masterPassword.hashCode ^
      myCode.hashCode ^
      newMemo.hashCode ^
      noDevices.hashCode ^
      opening.hashCode ^
      photoCamera.hashCode ^
      photoGallery.hashCode ^
      photoMissing.hashCode ^
      photoRemove.hashCode ^
      photoSize.hashCode ^
      save.hashCode ^
      scanHint.hashCode ^
      scanQr.hashCode ^
      syncDevices.hashCode ^
      syncNow.hashCode ^
      syncStarting.hashCode ^
      syncUnavailable.hashCode ^
      titleHint.hashCode ^
      unlock.hashCode ^
      unpair.hashCode ^
      color.hashCode ^
      changePassword.hashCode ^
      confirmPassword.hashCode ^
      createVault.hashCode ^
      currentPassword.hashCode ^
      forgotPassword.hashCode ^
      issueRecovery.hashCode ^
      newPassword.hashCode ^
      newVaultHint.hashCode ^
      noRecovery.hashCode ^
      passwordChanged.hashCode ^
      passwordHint.hashCode ^
      passwordMismatch.hashCode ^
      recoveryAbsent.hashCode ^
      recoveryAck.hashCode ^
      recoveryCode.hashCode ^
      recoveryHint.hashCode ^
      recoveryIssued.hashCode ^
      recoveryPresent.hashCode ^
      recoveryPrompt.hashCode ^
      recoveryWarning.hashCode ^
      reissueRecovery.hashCode ^
      resetDone.hashCode ^
      resetPassword.hashCode ^
      resetVault.hashCode ^
      resetVaultConfirm.hashCode ^
      resetVaultHint.hashCode ^
      securitySection.hashCode ^
      allow.hashCode ^
      deviceId.hashCode ^
      pairCancelWait.hashCode ^
      pairConnected.hashCode ^
      pairRequest.hashCode ^
      pairRequestHint.hashCode ^
      pairVerification.hashCode ^
      pairVerify.hashCode ^
      pairWaiting.hashCode ^
      pairWaitingHint.hashCode ^
      reject.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiStrings &&
          runtimeType == other.runtimeType &&
          addPhoto == other.addPhoto &&
          bodyHint == other.bodyHint &&
          cameraError == other.cameraError &&
          connected == other.connected &&
          copied == other.copied &&
          copy == other.copy &&
          disconnected == other.disconnected &&
          lanConnect == other.lanConnect &&
          lanDone == other.lanDone &&
          lanEnterCode == other.lanEnterCode &&
          lanMyCode == other.lanMyCode &&
          lanNotFound == other.lanNotFound &&
          lanPairing == other.lanPairing &&
          lanSearching == other.lanSearching &&
          daysUnit == other.daysUnit &&
          language == other.language &&
          languageAuto == other.languageAuto &&
          lockNow == other.lockNow &&
          lockOnBackground == other.lockOnBackground &&
          lockOnBackgroundHint == other.lockOnBackgroundHint &&
          lockSection == other.lockSection &&
          saved == other.saved &&
          settings == other.settings &&
          unlockDays == other.unlockDays &&
          unlockDaysHint == other.unlockDaysHint &&
          updateAvailable == other.updateAvailable &&
          updateCheck == other.updateCheck &&
          updateCheckHint == other.updateCheckHint &&
          updateChecking == other.updateChecking &&
          updateLatest == other.updateLatest &&
          updateNow == other.updateNow &&
          updateOpen == other.updateOpen &&
          updateSection == other.updateSection &&
          version == other.version &&
          cancel == other.cancel &&
          delete == other.delete &&
          deleteGroupHint == other.deleteGroupHint &&
          emptyFolder == other.emptyFolder &&
          folderName == other.folderName &&
          moveTo == other.moveTo &&
          newGroup == other.newGroup &&
          ok == other.ok &&
          rename == other.rename &&
          rootFolder == other.rootFolder &&
          listTitle == other.listTitle &&
          masterPassword == other.masterPassword &&
          myCode == other.myCode &&
          newMemo == other.newMemo &&
          noDevices == other.noDevices &&
          opening == other.opening &&
          photoCamera == other.photoCamera &&
          photoGallery == other.photoGallery &&
          photoMissing == other.photoMissing &&
          photoRemove == other.photoRemove &&
          photoSize == other.photoSize &&
          save == other.save &&
          scanHint == other.scanHint &&
          scanQr == other.scanQr &&
          syncDevices == other.syncDevices &&
          syncNow == other.syncNow &&
          syncStarting == other.syncStarting &&
          syncUnavailable == other.syncUnavailable &&
          titleHint == other.titleHint &&
          unlock == other.unlock &&
          unpair == other.unpair &&
          color == other.color &&
          changePassword == other.changePassword &&
          confirmPassword == other.confirmPassword &&
          createVault == other.createVault &&
          currentPassword == other.currentPassword &&
          forgotPassword == other.forgotPassword &&
          issueRecovery == other.issueRecovery &&
          newPassword == other.newPassword &&
          newVaultHint == other.newVaultHint &&
          noRecovery == other.noRecovery &&
          passwordChanged == other.passwordChanged &&
          passwordHint == other.passwordHint &&
          passwordMismatch == other.passwordMismatch &&
          recoveryAbsent == other.recoveryAbsent &&
          recoveryAck == other.recoveryAck &&
          recoveryCode == other.recoveryCode &&
          recoveryHint == other.recoveryHint &&
          recoveryIssued == other.recoveryIssued &&
          recoveryPresent == other.recoveryPresent &&
          recoveryPrompt == other.recoveryPrompt &&
          recoveryWarning == other.recoveryWarning &&
          reissueRecovery == other.reissueRecovery &&
          resetDone == other.resetDone &&
          resetPassword == other.resetPassword &&
          resetVault == other.resetVault &&
          resetVaultConfirm == other.resetVaultConfirm &&
          resetVaultHint == other.resetVaultHint &&
          securitySection == other.securitySection &&
          allow == other.allow &&
          deviceId == other.deviceId &&
          pairCancelWait == other.pairCancelWait &&
          pairConnected == other.pairConnected &&
          pairRequest == other.pairRequest &&
          pairRequestHint == other.pairRequestHint &&
          pairVerification == other.pairVerification &&
          pairVerify == other.pairVerify &&
          pairWaiting == other.pairWaiting &&
          pairWaitingHint == other.pairWaitingHint &&
          reject == other.reject;
}
