// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_vault`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// 코어가 돌려주는 에러 메시지의 언어를 정한다 (`"ko"` / `"en"`, `"ko-KR"` 같은 로캘도 됨).
///
/// 모르는 값이면 시스템 로캘로 추정한다. Dart 쪽 UI 문구는 Flutter 가 따로 관리하지만,
/// 코어 에러는 이 함수로 맞춰야 화면에서 언어가 섞이지 않는다. 다른 API 를 부르기 전에
/// 한 번 호출하면 되고, 언어를 바꿀 때마다 다시 부르면 된다.
Future<void> setLanguage({required String code}) =>
    RustLib.instance.api.crateApiSetLanguage(code: code);

/// 지금 쓰이는 코어 메시지 언어 코드.
Future<String> language() => RustLib.instance.api.crateApiLanguage();

/// 현재 언어의 모바일 문구를 모아 돌려준다.
Future<FfiStrings> mobileStrings() =>
    RustLib.instance.api.crateApiMobileStrings();

/// vault 열기(없으면 생성). `vault_dir` 는 동기화 대상 디렉터리,
/// `cache_db_path` 는 기기 로컬 SQLite 파일 경로.
Future<void> vaultOpen(
        {required String vaultDir,
        required String cacheDbPath,
        required String password}) =>
    RustLib.instance.api.crateApiVaultOpen(
        vaultDir: vaultDir, cacheDbPath: cacheDbPath, password: password);

/// vault 닫기 (로그아웃).
Future<void> vaultClose() => RustLib.instance.api.crateApiVaultClose();

/// 최근 수정순 메모 목록.
Future<List<FfiMemo>> memoList() => RustLib.instance.api.crateApiMemoList();

/// 메모 생성(id=None) 또는 수정(id=Some). 생성된/수정된 메모의 id 를 돌려준다.
Future<String> memoUpsert(
        {String? id, required String title, required String body}) =>
    RustLib.instance.api.crateApiMemoUpsert(id: id, title: title, body: body);

/// 메모 삭제.
Future<void> memoDelete({required String id}) =>
    RustLib.instance.api.crateApiMemoDelete(id: id);

/// 스티커 색상 팔레트 키 변경.
Future<void> memoSetColor({required String id, required String color}) =>
    RustLib.instance.api.crateApiMemoSetColor(id: id, color: color);

/// 스티커 불투명도(%) 변경. 범위를 벗어나면 코어가 잘라낸다.
Future<void> memoSetOpacity(
        {required String id, required PlatformInt64 opacity}) =>
    RustLib.instance.api.crateApiMemoSetOpacity(id: id, opacity: opacity);

/// 메모를 그룹으로 옮긴다. `group_id` 가 빈 문자열이면 최상위로 뺀다.
Future<void> memoSetGroup({required String id, required String groupId}) =>
    RustLib.instance.api.crateApiMemoSetGroup(id: id, groupId: groupId);

/// 전체 그룹 목록 (이름순).
Future<List<FfiGroup>> groupList() => RustLib.instance.api.crateApiGroupList();

/// 그룹 생성. 만들어진 그룹 id 를 돌려준다.
Future<String> groupCreate({required String name, required String parentId}) =>
    RustLib.instance.api.crateApiGroupCreate(name: name, parentId: parentId);

/// 그룹 이름 변경.
Future<void> groupRename({required String id, required String name}) =>
    RustLib.instance.api.crateApiGroupRename(id: id, name: name);

/// 그룹을 다른 그룹 밑으로 옮긴다. 자기 자손 밑으로는 옮길 수 없다(순환 방지).
Future<void> groupMove({required String id, required String parentId}) =>
    RustLib.instance.api.crateApiGroupMove(id: id, parentId: parentId);

/// 그룹 삭제. 안의 메모/하위 그룹은 지워지지 않고 상위로 올라온다.
Future<void> groupDelete({required String id}) =>
    RustLib.instance.api.crateApiGroupDelete(id: id);

/// 다른 기기의 로그를 병합해 로컬 상태를 갱신한다.
/// (전송 계층이 vault 디렉터리에 새 로그를 가져다 놓은 뒤 호출)
Future<void> syncRebuild() => RustLib.instance.api.crateApiSyncRebuild();

/// QR 스캔으로 받은 페어링 코드 검증 + 기기 ID 추출.
/// (모바일 Syncthing 연동 전까지는 검증/표시에만 쓴다.)
Future<String> pairingDecode({required String code}) =>
    RustLib.instance.api.crateApiPairingDecode(code: code);

/// Dart 로 넘기는 그룹(폴더) 표현.
class FfiGroup {
  final String id;
  final String name;
  final String parentId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const FfiGroup({
    required this.id,
    required this.name,
    required this.parentId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiGroup &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Dart 로 넘기는 메모 표현. (코어 `Memo` 와 동일 필드; frb 가 Dart 클래스로 변환)
class FfiMemo {
  final String id;
  final String title;
  final String body;
  final String color;
  final PlatformInt64 opacity;
  final String groupId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const FfiMemo({
    required this.id,
    required this.title,
    required this.body,
    required this.color,
    required this.opacity,
    required this.groupId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      body.hashCode ^
      color.hashCode ^
      opacity.hashCode ^
      groupId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiMemo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          body == other.body &&
          color == other.color &&
          opacity == other.opacity &&
          groupId == other.groupId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 모바일 UI 문구 한 벌 (현재 언어). Dart 가 시작할 때 한 번 받아 들고 쓴다.
///
/// 문구를 Dart 에 따로 두면 언어가 갈라진다 — 코어 에러는 카탈로그, 화면 문구는
/// 하드코딩이 되어 한쪽만 번역된다. 키를 **Rust 에서** 읽어 넘기므로 `ymemo-i18n` 의
/// "코드가 쓰는 키가 카탈로그에 있는지" 테스트가 모바일 문구까지 함께 지켜 준다.
/// (언어를 바꾼 뒤엔 [`set_language`] 를 부르고 이걸 다시 받으면 된다.)
class FfiStrings {
  final String bodyHint;
  final String listTitle;
  final String masterPassword;
  final String newMemo;
  final String opening;
  final String save;
  final String syncNow;
  final String titleHint;
  final String unlock;

  const FfiStrings({
    required this.bodyHint,
    required this.listTitle,
    required this.masterPassword,
    required this.newMemo,
    required this.opening,
    required this.save,
    required this.syncNow,
    required this.titleHint,
    required this.unlock,
  });

  @override
  int get hashCode =>
      bodyHint.hashCode ^
      listTitle.hashCode ^
      masterPassword.hashCode ^
      newMemo.hashCode ^
      opening.hashCode ^
      save.hashCode ^
      syncNow.hashCode ^
      titleHint.hashCode ^
      unlock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiStrings &&
          runtimeType == other.runtimeType &&
          bodyHint == other.bodyHint &&
          listTitle == other.listTitle &&
          masterPassword == other.masterPassword &&
          newMemo == other.newMemo &&
          opening == other.opening &&
          save == other.save &&
          syncNow == other.syncNow &&
          titleHint == other.titleHint &&
          unlock == other.unlock;
}
