// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1620579161;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'ymemo_ffi',
    ioDirectory: '../../crates/ymemo-ffi/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiGroupCreate(
      {required String name, required String parentId});

  Future<void> crateApiGroupDelete({required String id});

  Future<List<FfiGroup>> crateApiGroupList();

  Future<void> crateApiGroupMove(
      {required String id, required String parentId});

  Future<void> crateApiGroupRename({required String id, required String name});

  Future<String> crateApiLanguage();

  Future<void> crateApiMemoDelete({required String id});

  Future<List<FfiMemo>> crateApiMemoList();

  Future<void> crateApiMemoSetColor(
      {required String id, required String color});

  Future<void> crateApiMemoSetGroup(
      {required String id, required String groupId});

  Future<void> crateApiMemoSetOpacity(
      {required String id, required PlatformInt64 opacity});

  Future<String> crateApiMemoUpsert(
      {String? id, required String title, required String body});

  Future<FfiStrings> crateApiMobileStrings();

  Future<String> crateApiPairingDecode({required String code});

  Future<void> crateApiSetLanguage({required String code});

  Future<void> crateApiSyncRebuild();

  Future<void> crateApiVaultClose();

  Future<void> crateApiVaultOpen(
      {required String vaultDir,
      required String cacheDbPath,
      required String password});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiGroupCreate(
      {required String name, required String parentId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(parentId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupCreateConstMeta,
      argValues: [name, parentId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupCreateConstMeta => const TaskConstMeta(
        debugName: "group_create",
        argNames: ["name", "parentId"],
      );

  @override
  Future<void> crateApiGroupDelete({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupDeleteConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupDeleteConstMeta => const TaskConstMeta(
        debugName: "group_delete",
        argNames: ["id"],
      );

  @override
  Future<List<FfiGroup>> crateApiGroupList() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ffi_group,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupListConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupListConstMeta => const TaskConstMeta(
        debugName: "group_list",
        argNames: [],
      );

  @override
  Future<void> crateApiGroupMove(
      {required String id, required String parentId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(parentId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupMoveConstMeta,
      argValues: [id, parentId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupMoveConstMeta => const TaskConstMeta(
        debugName: "group_move",
        argNames: ["id", "parentId"],
      );

  @override
  Future<void> crateApiGroupRename({required String id, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupRenameConstMeta,
      argValues: [id, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupRenameConstMeta => const TaskConstMeta(
        debugName: "group_rename",
        argNames: ["id", "name"],
      );

  @override
  Future<String> crateApiLanguage() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLanguageConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanguageConstMeta => const TaskConstMeta(
        debugName: "language",
        argNames: [],
      );

  @override
  Future<void> crateApiMemoDelete({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoDeleteConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoDeleteConstMeta => const TaskConstMeta(
        debugName: "memo_delete",
        argNames: ["id"],
      );

  @override
  Future<List<FfiMemo>> crateApiMemoList() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ffi_memo,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoListConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoListConstMeta => const TaskConstMeta(
        debugName: "memo_list",
        argNames: [],
      );

  @override
  Future<void> crateApiMemoSetColor(
      {required String id, required String color}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(color, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoSetColorConstMeta,
      argValues: [id, color],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoSetColorConstMeta => const TaskConstMeta(
        debugName: "memo_set_color",
        argNames: ["id", "color"],
      );

  @override
  Future<void> crateApiMemoSetGroup(
      {required String id, required String groupId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(groupId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoSetGroupConstMeta,
      argValues: [id, groupId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoSetGroupConstMeta => const TaskConstMeta(
        debugName: "memo_set_group",
        argNames: ["id", "groupId"],
      );

  @override
  Future<void> crateApiMemoSetOpacity(
      {required String id, required PlatformInt64 opacity}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_i_64(opacity, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoSetOpacityConstMeta,
      argValues: [id, opacity],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoSetOpacityConstMeta => const TaskConstMeta(
        debugName: "memo_set_opacity",
        argNames: ["id", "opacity"],
      );

  @override
  Future<String> crateApiMemoUpsert(
      {String? id, required String title, required String body}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(id, serializer);
        sse_encode_String(title, serializer);
        sse_encode_String(body, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoUpsertConstMeta,
      argValues: [id, title, body],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoUpsertConstMeta => const TaskConstMeta(
        debugName: "memo_upsert",
        argNames: ["id", "title", "body"],
      );

  @override
  Future<FfiStrings> crateApiMobileStrings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_strings,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMobileStringsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMobileStringsConstMeta => const TaskConstMeta(
        debugName: "mobile_strings",
        argNames: [],
      );

  @override
  Future<String> crateApiPairingDecode({required String code}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPairingDecodeConstMeta,
      argValues: [code],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPairingDecodeConstMeta => const TaskConstMeta(
        debugName: "pairing_decode",
        argNames: ["code"],
      );

  @override
  Future<void> crateApiSetLanguage({required String code}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSetLanguageConstMeta,
      argValues: [code],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetLanguageConstMeta => const TaskConstMeta(
        debugName: "set_language",
        argNames: ["code"],
      );

  @override
  Future<void> crateApiSyncRebuild() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncRebuildConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncRebuildConstMeta => const TaskConstMeta(
        debugName: "sync_rebuild",
        argNames: [],
      );

  @override
  Future<void> crateApiVaultClose() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVaultCloseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultCloseConstMeta => const TaskConstMeta(
        debugName: "vault_close",
        argNames: [],
      );

  @override
  Future<void> crateApiVaultOpen(
      {required String vaultDir,
      required String cacheDbPath,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(vaultDir, serializer);
        sse_encode_String(cacheDbPath, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVaultOpenConstMeta,
      argValues: [vaultDir, cacheDbPath, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultOpenConstMeta => const TaskConstMeta(
        debugName: "vault_open",
        argNames: ["vaultDir", "cacheDbPath", "password"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  FfiGroup dco_decode_ffi_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FfiGroup(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      parentId: dco_decode_String(arr[2]),
      createdAt: dco_decode_i_64(arr[3]),
      updatedAt: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  FfiMemo dco_decode_ffi_memo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return FfiMemo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      body: dco_decode_String(arr[2]),
      color: dco_decode_String(arr[3]),
      opacity: dco_decode_i_64(arr[4]),
      groupId: dco_decode_String(arr[5]),
      createdAt: dco_decode_i_64(arr[6]),
      updatedAt: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  FfiStrings dco_decode_ffi_strings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return FfiStrings(
      bodyHint: dco_decode_String(arr[0]),
      cameraError: dco_decode_String(arr[1]),
      close: dco_decode_String(arr[2]),
      listTitle: dco_decode_String(arr[3]),
      masterPassword: dco_decode_String(arr[4]),
      newMemo: dco_decode_String(arr[5]),
      opening: dco_decode_String(arr[6]),
      save: dco_decode_String(arr[7]),
      scanHint: dco_decode_String(arr[8]),
      scanPairingUnavailable: dco_decode_String(arr[9]),
      scanQr: dco_decode_String(arr[10]),
      scanResult: dco_decode_String(arr[11]),
      syncNow: dco_decode_String(arr[12]),
      titleHint: dco_decode_String(arr[13]),
      unlock: dco_decode_String(arr[14]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<FfiGroup> dco_decode_list_ffi_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_group).toList();
  }

  @protected
  List<FfiMemo> dco_decode_list_ffi_memo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_memo).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  FfiGroup sse_decode_ffi_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_parentId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return FfiGroup(
        id: var_id,
        name: var_name,
        parentId: var_parentId,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  FfiMemo sse_decode_ffi_memo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_opacity = sse_decode_i_64(deserializer);
    var var_groupId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return FfiMemo(
        id: var_id,
        title: var_title,
        body: var_body,
        color: var_color,
        opacity: var_opacity,
        groupId: var_groupId,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  FfiStrings sse_decode_ffi_strings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bodyHint = sse_decode_String(deserializer);
    var var_cameraError = sse_decode_String(deserializer);
    var var_close = sse_decode_String(deserializer);
    var var_listTitle = sse_decode_String(deserializer);
    var var_masterPassword = sse_decode_String(deserializer);
    var var_newMemo = sse_decode_String(deserializer);
    var var_opening = sse_decode_String(deserializer);
    var var_save = sse_decode_String(deserializer);
    var var_scanHint = sse_decode_String(deserializer);
    var var_scanPairingUnavailable = sse_decode_String(deserializer);
    var var_scanQr = sse_decode_String(deserializer);
    var var_scanResult = sse_decode_String(deserializer);
    var var_syncNow = sse_decode_String(deserializer);
    var var_titleHint = sse_decode_String(deserializer);
    var var_unlock = sse_decode_String(deserializer);
    return FfiStrings(
        bodyHint: var_bodyHint,
        cameraError: var_cameraError,
        close: var_close,
        listTitle: var_listTitle,
        masterPassword: var_masterPassword,
        newMemo: var_newMemo,
        opening: var_opening,
        save: var_save,
        scanHint: var_scanHint,
        scanPairingUnavailable: var_scanPairingUnavailable,
        scanQr: var_scanQr,
        scanResult: var_scanResult,
        syncNow: var_syncNow,
        titleHint: var_titleHint,
        unlock: var_unlock);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<FfiGroup> sse_decode_list_ffi_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiGroup>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_group(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiMemo> sse_decode_list_ffi_memo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiMemo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_memo(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ffi_group(FfiGroup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.parentId, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_ffi_memo(FfiMemo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_i_64(self.opacity, serializer);
    sse_encode_String(self.groupId, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_ffi_strings(FfiStrings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bodyHint, serializer);
    sse_encode_String(self.cameraError, serializer);
    sse_encode_String(self.close, serializer);
    sse_encode_String(self.listTitle, serializer);
    sse_encode_String(self.masterPassword, serializer);
    sse_encode_String(self.newMemo, serializer);
    sse_encode_String(self.opening, serializer);
    sse_encode_String(self.save, serializer);
    sse_encode_String(self.scanHint, serializer);
    sse_encode_String(self.scanPairingUnavailable, serializer);
    sse_encode_String(self.scanQr, serializer);
    sse_encode_String(self.scanResult, serializer);
    sse_encode_String(self.syncNow, serializer);
    sse_encode_String(self.titleHint, serializer);
    sse_encode_String(self.unlock, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_ffi_group(
      List<FfiGroup> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_group(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_memo(List<FfiMemo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_memo(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
