// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiRelease dco_decode_box_autoadd_ffi_release(dynamic raw);

  @protected
  FfiSettings dco_decode_box_autoadd_ffi_settings(dynamic raw);

  @protected
  FfiAttachment dco_decode_ffi_attachment(dynamic raw);

  @protected
  FfiGroup dco_decode_ffi_group(dynamic raw);

  @protected
  FfiMemo dco_decode_ffi_memo(dynamic raw);

  @protected
  FfiPendingDevice dco_decode_ffi_pending_device(dynamic raw);

  @protected
  FfiRelease dco_decode_ffi_release(dynamic raw);

  @protected
  FfiSettings dco_decode_ffi_settings(dynamic raw);

  @protected
  FfiSharedDevice dco_decode_ffi_shared_device(dynamic raw);

  @protected
  FfiStrings dco_decode_ffi_strings(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FfiAttachment> dco_decode_list_ffi_attachment(dynamic raw);

  @protected
  List<FfiGroup> dco_decode_list_ffi_group(dynamic raw);

  @protected
  List<FfiMemo> dco_decode_list_ffi_memo(dynamic raw);

  @protected
  List<FfiPendingDevice> dco_decode_list_ffi_pending_device(dynamic raw);

  @protected
  List<FfiSharedDevice> dco_decode_list_ffi_shared_device(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FfiRelease? dco_decode_opt_box_autoadd_ffi_release(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiRelease sse_decode_box_autoadd_ffi_release(SseDeserializer deserializer);

  @protected
  FfiSettings sse_decode_box_autoadd_ffi_settings(SseDeserializer deserializer);

  @protected
  FfiAttachment sse_decode_ffi_attachment(SseDeserializer deserializer);

  @protected
  FfiGroup sse_decode_ffi_group(SseDeserializer deserializer);

  @protected
  FfiMemo sse_decode_ffi_memo(SseDeserializer deserializer);

  @protected
  FfiPendingDevice sse_decode_ffi_pending_device(SseDeserializer deserializer);

  @protected
  FfiRelease sse_decode_ffi_release(SseDeserializer deserializer);

  @protected
  FfiSettings sse_decode_ffi_settings(SseDeserializer deserializer);

  @protected
  FfiSharedDevice sse_decode_ffi_shared_device(SseDeserializer deserializer);

  @protected
  FfiStrings sse_decode_ffi_strings(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FfiAttachment> sse_decode_list_ffi_attachment(
      SseDeserializer deserializer);

  @protected
  List<FfiGroup> sse_decode_list_ffi_group(SseDeserializer deserializer);

  @protected
  List<FfiMemo> sse_decode_list_ffi_memo(SseDeserializer deserializer);

  @protected
  List<FfiPendingDevice> sse_decode_list_ffi_pending_device(
      SseDeserializer deserializer);

  @protected
  List<FfiSharedDevice> sse_decode_list_ffi_shared_device(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FfiRelease? sse_decode_opt_box_autoadd_ffi_release(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_release(
      FfiRelease self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_settings(
      FfiSettings self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_attachment(FfiAttachment self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_group(FfiGroup self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_memo(FfiMemo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_pending_device(
      FfiPendingDevice self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_release(FfiRelease self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_settings(FfiSettings self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_shared_device(
      FfiSharedDevice self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_strings(FfiStrings self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_attachment(
      List<FfiAttachment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_group(List<FfiGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_memo(List<FfiMemo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_pending_device(
      List<FfiPendingDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_shared_device(
      List<FfiSharedDevice> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_release(
      FfiRelease? self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
