// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1485735830;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'ymemo_ffi',
    ioDirectory: '../../crates/ymemo-ffi/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<FfiAttachment> crateApiAttachmentAdd(
      {required String memoId,
      required List<int> data,
      required String name,
      required String mime,
      required PlatformInt64 widthPx,
      required PlatformInt64 heightPx});

  Future<Uint8List> crateApiAttachmentBytes({required String hash});

  Future<bool> crateApiAttachmentHasBlob({required String hash});

  Future<List<FfiAttachment>> crateApiAttachmentList({required String memoId});

  Future<void> crateApiAttachmentRemove({required String id});

  Future<void> crateApiAttachmentSetWidth(
      {required String id, required PlatformInt64 widthEmMilli});

  Future<String> crateApiGroupCreate(
      {required String name, required String parentId});

  Future<void> crateApiGroupDelete({required String id});

  Future<List<FfiGroup>> crateApiGroupList();

  Future<void> crateApiGroupMove(
      {required String id, required String parentId});

  Future<void> crateApiGroupRename({required String id, required String name});

  Future<String?> crateApiLanCode();

  Future<String?> crateApiLanJoin(
      {required String code, required BigInt timeoutSecs});

  Future<List<String>> crateApiLanPollPaired();

  Future<String> crateApiLanStart();

  Future<void> crateApiLanStop();

  Future<String> crateApiLanguage();

  Future<void> crateApiMemoDelete({required String id});

  Future<List<FfiMemo>> crateApiMemoList();

  Future<void> crateApiMemoSetColor(
      {required String id, required String color});

  Future<void> crateApiMemoSetGroup(
      {required String id, required String groupId});

  Future<void> crateApiMemoSetOpacity(
      {required String id, required PlatformInt64 opacity});

  Future<String> crateApiMemoUpsert(
      {String? id, required String title, required String body});

  Future<FfiStrings> crateApiMobileStrings();

  Future<String> crateApiPairingDecode({required String code});

  Future<void> crateApiSetLanguage({required String code});

  Future<List<FfiSharedDevice>> crateApiSyncDevices();

  Future<void> crateApiSyncPairWith({required String code});

  Future<String> crateApiSyncPairingCode();

  Future<void> crateApiSyncRebuild();

  Future<bool> crateApiSyncRunning();

  Future<String> crateApiSyncStart(
      {required String binaryPath,
      required String homeDir,
      required String vaultDir});

  Future<void> crateApiSyncStop();

  Future<void> crateApiSyncUnpair({required String deviceId});

  Future<void> crateApiVaultClose();

  Future<void> crateApiVaultOpen(
      {required String vaultDir,
      required String cacheDbPath,
      required String password});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FfiAttachment> crateApiAttachmentAdd(
      {required String memoId,
      required List<int> data,
      required String name,
      required String mime,
      required PlatformInt64 widthPx,
      required PlatformInt64 heightPx}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(memoId, serializer);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_String(name, serializer);
        sse_encode_String(mime, serializer);
        sse_encode_i_64(widthPx, serializer);
        sse_encode_i_64(heightPx, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_attachment,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentAddConstMeta,
      argValues: [memoId, data, name, mime, widthPx, heightPx],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentAddConstMeta => const TaskConstMeta(
        debugName: "attachment_add",
        argNames: ["memoId", "data", "name", "mime", "widthPx", "heightPx"],
      );

  @override
  Future<Uint8List> crateApiAttachmentBytes({required String hash}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(hash, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentBytesConstMeta,
      argValues: [hash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentBytesConstMeta => const TaskConstMeta(
        debugName: "attachment_bytes",
        argNames: ["hash"],
      );

  @override
  Future<bool> crateApiAttachmentHasBlob({required String hash}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(hash, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentHasBlobConstMeta,
      argValues: [hash],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentHasBlobConstMeta => const TaskConstMeta(
        debugName: "attachment_has_blob",
        argNames: ["hash"],
      );

  @override
  Future<List<FfiAttachment>> crateApiAttachmentList({required String memoId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(memoId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ffi_attachment,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentListConstMeta,
      argValues: [memoId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentListConstMeta => const TaskConstMeta(
        debugName: "attachment_list",
        argNames: ["memoId"],
      );

  @override
  Future<void> crateApiAttachmentRemove({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentRemoveConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentRemoveConstMeta => const TaskConstMeta(
        debugName: "attachment_remove",
        argNames: ["id"],
      );

  @override
  Future<void> crateApiAttachmentSetWidth(
      {required String id, required PlatformInt64 widthEmMilli}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_i_64(widthEmMilli, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAttachmentSetWidthConstMeta,
      argValues: [id, widthEmMilli],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAttachmentSetWidthConstMeta => const TaskConstMeta(
        debugName: "attachment_set_width",
        argNames: ["id", "widthEmMilli"],
      );

  @override
  Future<String> crateApiGroupCreate(
      {required String name, required String parentId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(parentId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupCreateConstMeta,
      argValues: [name, parentId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupCreateConstMeta => const TaskConstMeta(
        debugName: "group_create",
        argNames: ["name", "parentId"],
      );

  @override
  Future<void> crateApiGroupDelete({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupDeleteConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupDeleteConstMeta => const TaskConstMeta(
        debugName: "group_delete",
        argNames: ["id"],
      );

  @override
  Future<List<FfiGroup>> crateApiGroupList() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ffi_group,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupListConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupListConstMeta => const TaskConstMeta(
        debugName: "group_list",
        argNames: [],
      );

  @override
  Future<void> crateApiGroupMove(
      {required String id, required String parentId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(parentId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupMoveConstMeta,
      argValues: [id, parentId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupMoveConstMeta => const TaskConstMeta(
        debugName: "group_move",
        argNames: ["id", "parentId"],
      );

  @override
  Future<void> crateApiGroupRename({required String id, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiGroupRenameConstMeta,
      argValues: [id, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGroupRenameConstMeta => const TaskConstMeta(
        debugName: "group_rename",
        argNames: ["id", "name"],
      );

  @override
  Future<String?> crateApiLanCode() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLanCodeConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanCodeConstMeta => const TaskConstMeta(
        debugName: "lan_code",
        argNames: [],
      );

  @override
  Future<String?> crateApiLanJoin(
      {required String code, required BigInt timeoutSecs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        sse_encode_u_64(timeoutSecs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLanJoinConstMeta,
      argValues: [code, timeoutSecs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanJoinConstMeta => const TaskConstMeta(
        debugName: "lan_join",
        argNames: ["code", "timeoutSecs"],
      );

  @override
  Future<List<String>> crateApiLanPollPaired() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLanPollPairedConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanPollPairedConstMeta => const TaskConstMeta(
        debugName: "lan_poll_paired",
        argNames: [],
      );

  @override
  Future<String> crateApiLanStart() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLanStartConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanStartConstMeta => const TaskConstMeta(
        debugName: "lan_start",
        argNames: [],
      );

  @override
  Future<void> crateApiLanStop() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLanStopConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanStopConstMeta => const TaskConstMeta(
        debugName: "lan_stop",
        argNames: [],
      );

  @override
  Future<String> crateApiLanguage() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLanguageConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanguageConstMeta => const TaskConstMeta(
        debugName: "language",
        argNames: [],
      );

  @override
  Future<void> crateApiMemoDelete({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoDeleteConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoDeleteConstMeta => const TaskConstMeta(
        debugName: "memo_delete",
        argNames: ["id"],
      );

  @override
  Future<List<FfiMemo>> crateApiMemoList() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ffi_memo,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoListConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoListConstMeta => const TaskConstMeta(
        debugName: "memo_list",
        argNames: [],
      );

  @override
  Future<void> crateApiMemoSetColor(
      {required String id, required String color}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(color, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoSetColorConstMeta,
      argValues: [id, color],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoSetColorConstMeta => const TaskConstMeta(
        debugName: "memo_set_color",
        argNames: ["id", "color"],
      );

  @override
  Future<void> crateApiMemoSetGroup(
      {required String id, required String groupId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_String(groupId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoSetGroupConstMeta,
      argValues: [id, groupId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoSetGroupConstMeta => const TaskConstMeta(
        debugName: "memo_set_group",
        argNames: ["id", "groupId"],
      );

  @override
  Future<void> crateApiMemoSetOpacity(
      {required String id, required PlatformInt64 opacity}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        sse_encode_i_64(opacity, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoSetOpacityConstMeta,
      argValues: [id, opacity],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoSetOpacityConstMeta => const TaskConstMeta(
        debugName: "memo_set_opacity",
        argNames: ["id", "opacity"],
      );

  @override
  Future<String> crateApiMemoUpsert(
      {String? id, required String title, required String body}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(id, serializer);
        sse_encode_String(title, serializer);
        sse_encode_String(body, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMemoUpsertConstMeta,
      argValues: [id, title, body],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMemoUpsertConstMeta => const TaskConstMeta(
        debugName: "memo_upsert",
        argNames: ["id", "title", "body"],
      );

  @override
  Future<FfiStrings> crateApiMobileStrings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_strings,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMobileStringsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMobileStringsConstMeta => const TaskConstMeta(
        debugName: "mobile_strings",
        argNames: [],
      );

  @override
  Future<String> crateApiPairingDecode({required String code}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPairingDecodeConstMeta,
      argValues: [code],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPairingDecodeConstMeta => const TaskConstMeta(
        debugName: "pairing_decode",
        argNames: ["code"],
      );

  @override
  Future<void> crateApiSetLanguage({required String code}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSetLanguageConstMeta,
      argValues: [code],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetLanguageConstMeta => const TaskConstMeta(
        debugName: "set_language",
        argNames: ["code"],
      );

  @override
  Future<List<FfiSharedDevice>> crateApiSyncDevices() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ffi_shared_device,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncDevicesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncDevicesConstMeta => const TaskConstMeta(
        debugName: "sync_devices",
        argNames: [],
      );

  @override
  Future<void> crateApiSyncPairWith({required String code}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncPairWithConstMeta,
      argValues: [code],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncPairWithConstMeta => const TaskConstMeta(
        debugName: "sync_pair_with",
        argNames: ["code"],
      );

  @override
  Future<String> crateApiSyncPairingCode() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncPairingCodeConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncPairingCodeConstMeta => const TaskConstMeta(
        debugName: "sync_pairing_code",
        argNames: [],
      );

  @override
  Future<void> crateApiSyncRebuild() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncRebuildConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncRebuildConstMeta => const TaskConstMeta(
        debugName: "sync_rebuild",
        argNames: [],
      );

  @override
  Future<bool> crateApiSyncRunning() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSyncRunningConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncRunningConstMeta => const TaskConstMeta(
        debugName: "sync_running",
        argNames: [],
      );

  @override
  Future<String> crateApiSyncStart(
      {required String binaryPath,
      required String homeDir,
      required String vaultDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(binaryPath, serializer);
        sse_encode_String(homeDir, serializer);
        sse_encode_String(vaultDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncStartConstMeta,
      argValues: [binaryPath, homeDir, vaultDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncStartConstMeta => const TaskConstMeta(
        debugName: "sync_start",
        argNames: ["binaryPath", "homeDir", "vaultDir"],
      );

  @override
  Future<void> crateApiSyncStop() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncStopConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncStopConstMeta => const TaskConstMeta(
        debugName: "sync_stop",
        argNames: [],
      );

  @override
  Future<void> crateApiSyncUnpair({required String deviceId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(deviceId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSyncUnpairConstMeta,
      argValues: [deviceId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncUnpairConstMeta => const TaskConstMeta(
        debugName: "sync_unpair",
        argNames: ["deviceId"],
      );

  @override
  Future<void> crateApiVaultClose() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVaultCloseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultCloseConstMeta => const TaskConstMeta(
        debugName: "vault_close",
        argNames: [],
      );

  @override
  Future<void> crateApiVaultOpen(
      {required String vaultDir,
      required String cacheDbPath,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(vaultDir, serializer);
        sse_encode_String(cacheDbPath, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVaultOpenConstMeta,
      argValues: [vaultDir, cacheDbPath, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultOpenConstMeta => const TaskConstMeta(
        debugName: "vault_open",
        argNames: ["vaultDir", "cacheDbPath", "password"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiAttachment dco_decode_ffi_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return FfiAttachment(
      id: dco_decode_String(arr[0]),
      memoId: dco_decode_String(arr[1]),
      hash: dco_decode_String(arr[2]),
      name: dco_decode_String(arr[3]),
      mime: dco_decode_String(arr[4]),
      widthPx: dco_decode_i_64(arr[5]),
      heightPx: dco_decode_i_64(arr[6]),
      widthEmMilli: dco_decode_i_64(arr[7]),
      createdAt: dco_decode_i_64(arr[8]),
    );
  }

  @protected
  FfiGroup dco_decode_ffi_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FfiGroup(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      parentId: dco_decode_String(arr[2]),
      createdAt: dco_decode_i_64(arr[3]),
      updatedAt: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  FfiMemo dco_decode_ffi_memo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return FfiMemo(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      body: dco_decode_String(arr[2]),
      color: dco_decode_String(arr[3]),
      opacity: dco_decode_i_64(arr[4]),
      groupId: dco_decode_String(arr[5]),
      createdAt: dco_decode_i_64(arr[6]),
      updatedAt: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  FfiSharedDevice dco_decode_ffi_shared_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiSharedDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      connected: dco_decode_bool(arr[2]),
    );
  }

  @protected
  FfiStrings dco_decode_ffi_strings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 38)
      throw Exception('unexpected arr length: expect 38 but see ${arr.length}');
    return FfiStrings(
      addPhoto: dco_decode_String(arr[0]),
      bodyHint: dco_decode_String(arr[1]),
      cameraError: dco_decode_String(arr[2]),
      close: dco_decode_String(arr[3]),
      connected: dco_decode_String(arr[4]),
      copied: dco_decode_String(arr[5]),
      copy: dco_decode_String(arr[6]),
      disconnected: dco_decode_String(arr[7]),
      lanConnect: dco_decode_String(arr[8]),
      lanDone: dco_decode_String(arr[9]),
      lanEnterCode: dco_decode_String(arr[10]),
      lanMyCode: dco_decode_String(arr[11]),
      lanNotFound: dco_decode_String(arr[12]),
      lanPairing: dco_decode_String(arr[13]),
      lanSearching: dco_decode_String(arr[14]),
      listTitle: dco_decode_String(arr[15]),
      masterPassword: dco_decode_String(arr[16]),
      myCode: dco_decode_String(arr[17]),
      newMemo: dco_decode_String(arr[18]),
      noDevices: dco_decode_String(arr[19]),
      opening: dco_decode_String(arr[20]),
      pairAdded: dco_decode_String(arr[21]),
      photoCamera: dco_decode_String(arr[22]),
      photoGallery: dco_decode_String(arr[23]),
      photoMissing: dco_decode_String(arr[24]),
      photoRemove: dco_decode_String(arr[25]),
      photoSize: dco_decode_String(arr[26]),
      save: dco_decode_String(arr[27]),
      scanHint: dco_decode_String(arr[28]),
      scanQr: dco_decode_String(arr[29]),
      scanResult: dco_decode_String(arr[30]),
      syncDevices: dco_decode_String(arr[31]),
      syncNow: dco_decode_String(arr[32]),
      syncStarting: dco_decode_String(arr[33]),
      syncUnavailable: dco_decode_String(arr[34]),
      titleHint: dco_decode_String(arr[35]),
      unlock: dco_decode_String(arr[36]),
      unpair: dco_decode_String(arr[37]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FfiAttachment> dco_decode_list_ffi_attachment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_attachment).toList();
  }

  @protected
  List<FfiGroup> dco_decode_list_ffi_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_group).toList();
  }

  @protected
  List<FfiMemo> dco_decode_list_ffi_memo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_memo).toList();
  }

  @protected
  List<FfiSharedDevice> dco_decode_list_ffi_shared_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_shared_device).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiAttachment sse_decode_ffi_attachment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_memoId = sse_decode_String(deserializer);
    var var_hash = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_mime = sse_decode_String(deserializer);
    var var_widthPx = sse_decode_i_64(deserializer);
    var var_heightPx = sse_decode_i_64(deserializer);
    var var_widthEmMilli = sse_decode_i_64(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return FfiAttachment(
        id: var_id,
        memoId: var_memoId,
        hash: var_hash,
        name: var_name,
        mime: var_mime,
        widthPx: var_widthPx,
        heightPx: var_heightPx,
        widthEmMilli: var_widthEmMilli,
        createdAt: var_createdAt);
  }

  @protected
  FfiGroup sse_decode_ffi_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_parentId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return FfiGroup(
        id: var_id,
        name: var_name,
        parentId: var_parentId,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  FfiMemo sse_decode_ffi_memo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_opacity = sse_decode_i_64(deserializer);
    var var_groupId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return FfiMemo(
        id: var_id,
        title: var_title,
        body: var_body,
        color: var_color,
        opacity: var_opacity,
        groupId: var_groupId,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt);
  }

  @protected
  FfiSharedDevice sse_decode_ffi_shared_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_connected = sse_decode_bool(deserializer);
    return FfiSharedDevice(
        id: var_id, name: var_name, connected: var_connected);
  }

  @protected
  FfiStrings sse_decode_ffi_strings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_addPhoto = sse_decode_String(deserializer);
    var var_bodyHint = sse_decode_String(deserializer);
    var var_cameraError = sse_decode_String(deserializer);
    var var_close = sse_decode_String(deserializer);
    var var_connected = sse_decode_String(deserializer);
    var var_copied = sse_decode_String(deserializer);
    var var_copy = sse_decode_String(deserializer);
    var var_disconnected = sse_decode_String(deserializer);
    var var_lanConnect = sse_decode_String(deserializer);
    var var_lanDone = sse_decode_String(deserializer);
    var var_lanEnterCode = sse_decode_String(deserializer);
    var var_lanMyCode = sse_decode_String(deserializer);
    var var_lanNotFound = sse_decode_String(deserializer);
    var var_lanPairing = sse_decode_String(deserializer);
    var var_lanSearching = sse_decode_String(deserializer);
    var var_listTitle = sse_decode_String(deserializer);
    var var_masterPassword = sse_decode_String(deserializer);
    var var_myCode = sse_decode_String(deserializer);
    var var_newMemo = sse_decode_String(deserializer);
    var var_noDevices = sse_decode_String(deserializer);
    var var_opening = sse_decode_String(deserializer);
    var var_pairAdded = sse_decode_String(deserializer);
    var var_photoCamera = sse_decode_String(deserializer);
    var var_photoGallery = sse_decode_String(deserializer);
    var var_photoMissing = sse_decode_String(deserializer);
    var var_photoRemove = sse_decode_String(deserializer);
    var var_photoSize = sse_decode_String(deserializer);
    var var_save = sse_decode_String(deserializer);
    var var_scanHint = sse_decode_String(deserializer);
    var var_scanQr = sse_decode_String(deserializer);
    var var_scanResult = sse_decode_String(deserializer);
    var var_syncDevices = sse_decode_String(deserializer);
    var var_syncNow = sse_decode_String(deserializer);
    var var_syncStarting = sse_decode_String(deserializer);
    var var_syncUnavailable = sse_decode_String(deserializer);
    var var_titleHint = sse_decode_String(deserializer);
    var var_unlock = sse_decode_String(deserializer);
    var var_unpair = sse_decode_String(deserializer);
    return FfiStrings(
        addPhoto: var_addPhoto,
        bodyHint: var_bodyHint,
        cameraError: var_cameraError,
        close: var_close,
        connected: var_connected,
        copied: var_copied,
        copy: var_copy,
        disconnected: var_disconnected,
        lanConnect: var_lanConnect,
        lanDone: var_lanDone,
        lanEnterCode: var_lanEnterCode,
        lanMyCode: var_lanMyCode,
        lanNotFound: var_lanNotFound,
        lanPairing: var_lanPairing,
        lanSearching: var_lanSearching,
        listTitle: var_listTitle,
        masterPassword: var_masterPassword,
        myCode: var_myCode,
        newMemo: var_newMemo,
        noDevices: var_noDevices,
        opening: var_opening,
        pairAdded: var_pairAdded,
        photoCamera: var_photoCamera,
        photoGallery: var_photoGallery,
        photoMissing: var_photoMissing,
        photoRemove: var_photoRemove,
        photoSize: var_photoSize,
        save: var_save,
        scanHint: var_scanHint,
        scanQr: var_scanQr,
        scanResult: var_scanResult,
        syncDevices: var_syncDevices,
        syncNow: var_syncNow,
        syncStarting: var_syncStarting,
        syncUnavailable: var_syncUnavailable,
        titleHint: var_titleHint,
        unlock: var_unlock,
        unpair: var_unpair);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiAttachment> sse_decode_list_ffi_attachment(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiAttachment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_attachment(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiGroup> sse_decode_list_ffi_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiGroup>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_group(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiMemo> sse_decode_list_ffi_memo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiMemo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_memo(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiSharedDevice> sse_decode_list_ffi_shared_device(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiSharedDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_shared_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_ffi_attachment(FfiAttachment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.memoId, serializer);
    sse_encode_String(self.hash, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.mime, serializer);
    sse_encode_i_64(self.widthPx, serializer);
    sse_encode_i_64(self.heightPx, serializer);
    sse_encode_i_64(self.widthEmMilli, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_ffi_group(FfiGroup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.parentId, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_ffi_memo(FfiMemo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_i_64(self.opacity, serializer);
    sse_encode_String(self.groupId, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_ffi_shared_device(
      FfiSharedDevice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.connected, serializer);
  }

  @protected
  void sse_encode_ffi_strings(FfiStrings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.addPhoto, serializer);
    sse_encode_String(self.bodyHint, serializer);
    sse_encode_String(self.cameraError, serializer);
    sse_encode_String(self.close, serializer);
    sse_encode_String(self.connected, serializer);
    sse_encode_String(self.copied, serializer);
    sse_encode_String(self.copy, serializer);
    sse_encode_String(self.disconnected, serializer);
    sse_encode_String(self.lanConnect, serializer);
    sse_encode_String(self.lanDone, serializer);
    sse_encode_String(self.lanEnterCode, serializer);
    sse_encode_String(self.lanMyCode, serializer);
    sse_encode_String(self.lanNotFound, serializer);
    sse_encode_String(self.lanPairing, serializer);
    sse_encode_String(self.lanSearching, serializer);
    sse_encode_String(self.listTitle, serializer);
    sse_encode_String(self.masterPassword, serializer);
    sse_encode_String(self.myCode, serializer);
    sse_encode_String(self.newMemo, serializer);
    sse_encode_String(self.noDevices, serializer);
    sse_encode_String(self.opening, serializer);
    sse_encode_String(self.pairAdded, serializer);
    sse_encode_String(self.photoCamera, serializer);
    sse_encode_String(self.photoGallery, serializer);
    sse_encode_String(self.photoMissing, serializer);
    sse_encode_String(self.photoRemove, serializer);
    sse_encode_String(self.photoSize, serializer);
    sse_encode_String(self.save, serializer);
    sse_encode_String(self.scanHint, serializer);
    sse_encode_String(self.scanQr, serializer);
    sse_encode_String(self.scanResult, serializer);
    sse_encode_String(self.syncDevices, serializer);
    sse_encode_String(self.syncNow, serializer);
    sse_encode_String(self.syncStarting, serializer);
    sse_encode_String(self.syncUnavailable, serializer);
    sse_encode_String(self.titleHint, serializer);
    sse_encode_String(self.unlock, serializer);
    sse_encode_String(self.unpair, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_attachment(
      List<FfiAttachment> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_attachment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_group(
      List<FfiGroup> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_group(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_memo(List<FfiMemo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_memo(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_shared_device(
      List<FfiSharedDevice> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_shared_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
