// Windows release builds run as a GUI subsystem app: without this a cmd window opens
// alongside, and closing it kills the app. Debug builds keep the console for println.
#![cfg_attr(all(windows, not(debug_assertions)), windows_subsystem = "windows")]
//! Ymemo desktop app (Slint): a tray-resident sticky-note app.
//!
//! Windows:
//!  - `LockWindow` — master password on startup, opening or creating the vault.
//!  - `ListWindow` — the memo list, toggled from the tray icon.
//!  - `StickyWindow` — one frameless window per memo. The body is the editor (debounced
//!    autosave), the title bar drags it around, a double click folds it to a thin bar,
//!    + adds a memo and x closes the window without deleting anything.
//!
//! Closing every window leaves the app in the tray (`run_event_loop_until_quit`); only the
//! tray menu quits.


use std::cell::{Cell, RefCell};
use std::collections::{HashMap, HashSet};
use std::rc::Rc;
use std::time::{Duration, Instant};

use anyhow::Result;
use slint::{ComponentHandle, ModelRc, SharedString, TimerMode, VecModel};
use ymemo_core::{
    crypto::MasterKey, history::Entity, lan_pair, now_millis, pairing::PairingCode,
    sync::Syncthing, vault::Vault, Store,
};

use settings::Settings;
use ymemo_i18n::t;

slint::include_modules!();

// `apply_strings`, generated by build.rs from the i18n catalog.
include!(concat!(env!("OUT_DIR"), "/i18n_apply.rs"));

mod history;
mod icon;
mod instance;
mod list;
mod lock;
mod pairing;
mod security;
mod settings;
mod state;
mod sticky;
mod sync;
mod tray;
mod update;
mod window;

use icon::set_window_icon;
use list::{move_row, refresh_list};
use lock::{
    apply_lang, apply_opened_vault, fill_settings_window, lock_now, reset_vault,
    start_unlock_session,
};
use pairing::qr_image;
use state::{touch, AppUi, Ctx, APP};
use sticky::{close_sticky, new_memo, open_sticky, snap_tick, SNAP_INTERVAL};
use sync::{start_merge_timer, start_syncthing, SYNC_FOLDER_ID};
use window::present;

/// How often idleness is checked; fine-grained enough against a setting in minutes.
const IDLE_CHECK_INTERVAL: Duration = Duration::from_secs(20);


/// Picks the Slint renderer; call once before creating any window.
///
/// The default renderer (femtovg) needs OpenGL 2.0+, but Windows machines often have no GPU
/// driver or only legacy GL 1.1 under a VM or RDP, where even `glCreateShader` is missing.
/// So Windows defaults to the CPU renderer, which is plenty for this UI. Override with
/// `YMEMO_RENDERER=femtovg|software|skia`. Linux and macOS keep the default.
fn select_renderer() {
    let name = match std::env::var("YMEMO_RENDERER") {
        Ok(n) if !n.is_empty() => n,
        _ if cfg!(windows) => "software".to_string(),
        _ => return, // keep the default where GL works
    };
    match i_slint_backend_winit::Backend::builder()
        .with_renderer_name(name.as_str())
        .build()
    {
        Ok(backend) => {
            if let Err(e) = slint::platform::set_platform(Box::new(backend)) {
                eprintln!("could not select renderer '{name}', continuing with the default: {e:?}");
            }
        }
        Err(e) => eprintln!("could not build the '{name}' backend, continuing with the default: {e}"),
    }
}

/// Platform data directory, e.g. ~/.local/share/ymemo on Linux, %APPDATA%\ymemo\Ymemo\data
/// on Windows.
///
/// Only the path; nothing is created. `--quit` and `--purge` run before the directory should
/// exist, and creating it on the way to deleting it is how `--purge` used to report success
/// on a machine that had nothing left to delete.
fn data_dir() -> std::path::PathBuf {
    match directories::ProjectDirs::from("dev", "ymemo", "Ymemo") {
        Some(dirs) => dirs.data_dir().to_path_buf(),
        // Last resort for a machine with no home directory at all.
        None => std::path::PathBuf::from("."),
    }
}

/// Deletes this device's data directory: vault, cache, session, settings and the sync
/// daemon's own configuration.
///
/// The running instance is stopped first, and not only because it holds the cache open:
/// Syncthing propagates deletions, so removing the vault while the daemon still carries it
/// would empty the memos on every paired device too. If the app will not quit, nothing is
/// deleted. Copies on other devices are never touched.
fn purge(dir: &std::path::Path) -> Result<()> {
    // Never act on data_dir()'s fallback: deleting the working directory is not something to
    // do on one's own initiative.
    if dir == std::path::Path::new(".") {
        anyhow::bail!("no data directory to delete on this platform");
    }
    // Before asking anything to quit: the lock file the check needs lives in this very
    // directory, so an absent one can hold neither data nor a running instance.
    if !dir.exists() {
        println!("nothing to delete: {}", dir.display());
        return Ok(());
    }
    // Returns true when the lock is free, so a machine with nothing running passes too.
    if !instance::quit_running(dir) {
        anyhow::bail!("Ymemo is still running; close it and try again");
    }
    std::fs::remove_dir_all(dir)?;
    println!("deleted {}", dir.display());
    Ok(())
}

fn main() -> Result<()> {
    // Magnetic snapping needs to read and set window coordinates, which native Wayland
    // forbids; with XWayland available, drop WAYLAND_DISPLAY so winit takes X11.
    // YMEMO_FORCE_WAYLAND=1 keeps Wayland and loses snapping.
    if std::env::var_os("YMEMO_FORCE_WAYLAND").is_none() && std::env::var_os("DISPLAY").is_some() {
        std::env::remove_var("WAYLAND_DISPLAY");
    }

    let dir = data_dir();

    // `ymemo --quit` is not a session, it is a message: tell a running instance to save and
    // exit, wait for it, and return. Installers and package scripts use it to get the app and
    // its sync daemon out of the way without killing them (see packaging/).
    if std::env::args().skip(1).any(|a| a == "--quit") {
        return if instance::quit_running(&dir) {
            Ok(())
        } else {
            Err(anyhow::anyhow!("Ymemo did not quit within the timeout"))
        };
    }

    // `ymemo --purge` deletes everything this device stores and exits. It is what the
    // Windows uninstaller offers on the way out, and the only way to do the same on Linux,
    // where a package may not touch a user's home directory.
    if std::env::args().skip(1).any(|a| a == "--purge") {
        return purge(&dir);
    }

    // Only one instance per user: a second one would run a second sync daemon over the same
    // syncthing home and write the same cache. It happens easily enough — the Windows
    // installer's startup task plus a click on the icon of an app that lives in the tray.
    // From here on this is a real session, so the directory has to exist.
    let _ = std::fs::create_dir_all(&dir);

    let Some(_instance) = instance::acquire(&dir) else {
        instance::send_show(&dir); // hand the running one the foreground instead
        eprintln!("Ymemo is already running; asked it to show itself");
        return Ok(());
    };
    instance::serve(&dir);

    select_renderer();

    let lock = LockWindow::new()?;
    let list = ListWindow::new()?;

    // Syncthing starts before unlocking (it needs no key), so a new device can pair first,
    // receive vault.json and the logs, and only then be asked for the password.
    let vault_dir = dir.join("vault");
    let _ = std::fs::create_dir_all(&vault_dir);
    let st = start_syncthing(&dir, &vault_dir);
    let mut my_device_id: Option<String> = None;
    if let Some(st) = &st {
        match st.device_id() {
            Ok(id) => {
                let code = PairingCode::new(&id).encode();
                if let Some(img) = qr_image(&code) {
                    lock.set_qr_image(img);
                }
                if let Some(img) = qr_image(&code) {
                    list.set_qr_image(img);
                }
                lock.set_my_pairing_code(SharedString::from(code.clone()));
                list.set_my_pairing_code(SharedString::from(code));
                lock.set_sync_available(true);
                list.set_sync_available(true);
                my_device_id = Some(id);
            }
            Err(e) => eprintln!("could not read the device id: {e}"),
        }
    }
    // Dropping this on exit shuts the daemon down.
    let syncthing: Rc<RefCell<Option<Syncthing>>> = Rc::new(RefCell::new(st));

    // LAN pairing listener: swaps device ids over a 6-digit code, only once our own id is
    // known, since that is what it answers with.
    let lan = my_device_id
        .as_ref()
        .and_then(|id| match lan_pair::PairListener::start(id.clone()) {
            Ok(l) => Some(Rc::new(l)),
            Err(e) => {
                eprintln!("LAN pairing unavailable, continuing without it: {e}");
                None
            }
        });

    let mut loaded = Settings::load(&dir);
    loaded.sanitize();
    let ctx = Ctx {
        vault: Rc::new(RefCell::new(None)),
        model: Rc::new(VecModel::from(Vec::<ListRow>::new())),
        stickies: Rc::new(RefCell::new(HashMap::new())),
        collapsed: Rc::new(RefCell::new(HashSet::new())),
        dir: Rc::new(dir.clone()),
        settings: Rc::new(RefCell::new(loaded)),
        last_activity: Rc::new(Cell::new(Instant::now())),
    };
    list.set_rows(ModelRc::from(ctx.model.clone()));
    let unlocked = Rc::new(Cell::new(false));

    // The settings and security windows are built once and only shown or hidden; rebuilding
    // them would reset their position every time.
    let settings_win = SettingsWindow::new()?;
    let security_win = SecurityWindow::new()?;
    let history_win = HistoryWindow::new()?;
    apply_lang(&ctx, &lock, &list, &settings_win, &security_win, &history_win);
    security::wire(&ctx, &settings_win, &security_win);

    // ---- Past versions of a memo or folder. ----
    let history_subject: history::Subject = Rc::new(RefCell::new(None));
    history::wire(&ctx, &history_win, &history_subject);
    {
        let ctx = ctx.clone();
        let win = history_win.as_weak();
        let subject = history_subject.clone();
        list.on_show_history(move |id, is_group| {
            touch(&ctx);
            let Some(w) = win.upgrade() else { return };
            let entity = if is_group { Entity::Group } else { Entity::Memo };
            history::show(&ctx, &w, &subject, entity, &id);
        });
    }

    // First run? A vault.json means an existing vault (unlock); without one this is a new
    // device (create, or link to an existing one). Without the distinction a new device
    // would create a vault with its own salt before pairing delivers vault.json, and the
    // keys would diverge.
    let vault_exists = vault_dir.join("vault.json").exists();
    lock.set_vault_exists(vault_exists);
    lock.set_has_recovery(ymemo_core::vault::recovery_code_exists(&vault_dir));

    // A vault created on this device waits here while its recovery code is on screen: it is
    // opened only once the user confirms they wrote the code down.
    let pending_vault: Rc<RefCell<Option<Vault>>> = Rc::new(RefCell::new(None));

    // ---- Stay unlocked: a valid session key skips the password prompt. ----
    // On any failure (wrong key, damaged cache, diverged key) the session is dropped and the
    // lock screen comes up.
    let auto_unlocked = vault_exists
        && settings::load_session(&dir).is_some_and(|key_bytes| {
            let opened = MasterKey::from_bytes(&key_bytes)
                .and_then(|key| {
                    let store = Store::open(dir.join("ymemo.db"))?;
                    Vault::open_with_key(vault_dir.clone(), key, store)
                });
            match opened {
                Ok(v) => {
                    apply_opened_vault(v, &ctx, &lock, &list.as_weak(), &unlocked);
                    true
                }
                Err(e) => {
                    eprintln!("could not unlock from the session, asking for the password: {e}");
                    settings::clear_session(&dir);
                    false
                }
            }
        });

    // ---- Lock window: open an existing vault, or create one. ----
    {
        let ctx = ctx.clone();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let unlocked = unlocked.clone();
        let dir = dir.clone();
        // Open: derive the key from vault.json's salt; a diverged key heals inside open.
        // **Never fall back to create** — that is what made keys diverge in the first place.
        lock.on_unlock(move |password| {
            let lock = lock_weak.unwrap();
            if password.is_empty() {
                lock.set_lock_message(t!("msg.enter_password").into());
                return;
            }
            let store = match Store::open(dir.join("ymemo.db")) {
                Ok(s) => s,
                Err(e) => {
                    lock.set_lock_message(SharedString::from(t!("msg.cache_open_failed", error = e)));
                    return;
                }
            };
            // Argon2id blocks the UI for a few hundred ms, but only on the lock screen.
            match Vault::open(dir.join("vault"), password.as_bytes(), store) {
                Ok(v) => {
                    start_unlock_session(&ctx, &v);
                    apply_opened_vault(v, &ctx, &lock, &list_weak, &unlocked);
                }
                Err(e) => lock.set_lock_message(SharedString::from(format!("{e}"))),
            }
        });
    }
    {
        let ctx = ctx.clone();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let unlocked = unlocked.clone();
        let dir = dir.clone();
        let syncthing = syncthing.clone();
        let pending_vault = pending_vault.clone();
        // Create: only on a device starting fresh. The salt is generated exactly here.
        lock.on_create_vault(move |password| {
            let lock = lock_weak.unwrap();
            if password.is_empty() {
                lock.set_lock_message(t!("msg.enter_new_password").into());
                return;
            }
            let store = match Store::open(dir.join("ymemo.db")) {
                Ok(s) => s,
                Err(e) => {
                    lock.set_lock_message(SharedString::from(t!("msg.cache_open_failed", error = e)));
                    return;
                }
            };
            match Vault::open_or_create(dir.join("vault"), password.as_bytes(), store) {
                Ok(v) => {
                    // Register the folder here as well as at startup: a reset removes it
                    // deliberately, and this is the first vault that follows one.
                    if let Some(st) = syncthing.borrow().as_ref() {
                        if let Err(e) =
                            st.ensure_folder(SYNC_FOLDER_ID, "Ymemo Vault", &dir.join("vault"))
                        {
                            eprintln!("could not register the shared folder: {e}");
                        }
                    }
                    start_unlock_session(&ctx, &v);
                    // Show the recovery code before anything else; the vault waits in
                    // `pending_vault` until the user confirms they have written it down.
                    match v.issue_recovery_code() {
                        Ok(code) => {
                            lock.set_lock_message(SharedString::new());
                            lock.set_new_recovery_code(SharedString::from(code));
                            *pending_vault.borrow_mut() = Some(v);
                        }
                        // A vault without a recovery code still works, so this never blocks
                        // the user out of the app they just set up.
                        Err(e) => {
                            eprintln!("could not issue a recovery code: {e}");
                            lock.set_vault_exists(true);
                            apply_opened_vault(v, &ctx, &lock, &list_weak, &unlocked);
                        }
                    }
                }
                Err(e) => lock.set_lock_message(SharedString::from(format!("{e}"))),
            }
        });
    }

    // ---- Recovery code written down: open the vault that was waiting for it. ----
    {
        let ctx = ctx.clone();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let unlocked = unlocked.clone();
        let pending_vault = pending_vault.clone();
        lock.on_recovery_ack(move || {
            let Some(v) = pending_vault.borrow_mut().take() else { return };
            let lock = lock_weak.unwrap();
            lock.set_new_recovery_code(SharedString::new());
            lock.set_vault_exists(true);
            lock.set_has_recovery(true);
            apply_opened_vault(v, &ctx, &lock, &list_weak, &unlocked);
        });
    }

    // ---- Forgotten password: the recovery code sets a new one. ----
    {
        let ctx = ctx.clone();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let unlocked = unlocked.clone();
        let dir = dir.clone();
        lock.on_recover(move |code, new_password| {
            let lock = lock_weak.unwrap();
            let vault_dir = dir.join("vault");
            // Only the header is rewritten, so a wrong code costs one Argon2id run and
            // leaves the vault exactly as it was.
            if let Err(e) = ymemo_core::vault::reset_password_with_recovery(
                &vault_dir,
                &code,
                new_password.as_bytes(),
            ) {
                lock.set_lock_message(SharedString::from(format!("{e}")));
                return;
            }
            let store = match Store::open(dir.join("ymemo.db")) {
                Ok(s) => s,
                Err(e) => {
                    lock.set_lock_message(SharedString::from(t!("msg.cache_open_failed", error = e)));
                    return;
                }
            };
            match Vault::open(&vault_dir, new_password.as_bytes(), store) {
                Ok(v) => {
                    start_unlock_session(&ctx, &v);
                    lock.invoke_leave_recovery();
                    lock.set_lock_message(SharedString::new());
                    apply_opened_vault(v, &ctx, &lock, &list_weak, &unlocked);
                }
                Err(e) => lock.set_lock_message(SharedString::from(format!("{e}"))),
            }
        });
    }

    // ---- Forgotten password, no recovery code: wipe and start over. ----
    {
        let ctx = ctx.clone();
        let lock_weak = lock.as_weak();
        let syncthing = syncthing.clone();
        lock.on_reset_vault(move || {
            let lock = lock_weak.unwrap();
            match reset_vault(&ctx, &syncthing) {
                Ok(()) => {
                    lock.invoke_leave_recovery();
                    lock.invoke_clear_password();
                    lock.set_vault_exists(false);
                    lock.set_has_recovery(false);
                    lock.set_lock_message(SharedString::from(t!("msg.reset_done")));
                }
                Err(e) => {
                    lock.set_lock_message(SharedString::from(t!("msg.reset_failed", error = e)))
                }
            }
        });
    }

    // ---- List window: open, add, delete. ----
    {
        let ctx = ctx.clone();
        list.on_open_memo(move |id| {
            touch(&ctx);
            let memo = {
                let guard = ctx.vault.borrow();
                let Some(v) = guard.as_ref() else { return };
                match v.store().get(&id) {
                    Ok(Some(m)) => m,
                    _ => return,
                }
            };
            if let Err(e) = open_sticky(&ctx, &memo, false) {
                eprintln!("could not open the sticky window: {e}");
            }
        });
    }
    {
        let ctx = ctx.clone();
        list.on_new_memo(move || new_memo(&ctx));
    }
    {
        let ctx = ctx.clone();
        list.on_delete_row(move |id, is_group| {
            touch(&ctx);
            {
                let mut guard = ctx.vault.borrow_mut();
                let Some(v) = guard.as_mut() else { return };
                // Deleting a group lifts its contents instead of removing them.
                let res = if is_group { v.delete_group(&id) } else { v.delete(&id) };
                if let Err(e) = res {
                    eprintln!("delete failed: {e}");
                    return;
                }
                refresh_list(v, &ctx.model, &ctx.collapsed.borrow());
            }
            if !is_group {
                close_sticky(&ctx.stickies, id.as_str()); // clean up an open sticky
            }
        });
    }

    // ---- Groups: create, expand/collapse, rename, drag to move. ----
    {
        let ctx = ctx.clone();
        let list_weak = list.as_weak();
        list.on_new_group(move || {
            touch(&ctx);
            let group = ymemo_core::Group::new(t!("msg.new_group_name"));
            {
                let mut guard = ctx.vault.borrow_mut();
                let Some(v) = guard.as_mut() else { return };
                if let Err(e) = v.upsert_group(&group) {
                    eprintln!("could not create the group: {e}");
                    return;
                }
                refresh_list(v, &ctx.model, &ctx.collapsed.borrow());
            }
            // Go straight into rename mode so the user can type.
            if let Some(w) = list_weak.upgrade() {
                w.set_editing_text(SharedString::from(group.name.clone()));
                w.set_editing_id(SharedString::from(group.id));
            }
        });
    }
    {
        let ctx = ctx.clone();
        list.on_toggle_group(move |id| {
            touch(&ctx);
            {
                let mut collapsed = ctx.collapsed.borrow_mut();
                if !collapsed.remove(id.as_str()) {
                    collapsed.insert(id.to_string());
                }
            }
            let guard = ctx.vault.borrow();
            let Some(v) = guard.as_ref() else { return };
            refresh_list(v, &ctx.model, &ctx.collapsed.borrow());
        });
    }
    {
        let ctx = ctx.clone();
        list.on_rename_group(move |id, name| {
            touch(&ctx);
            let mut guard = ctx.vault.borrow_mut();
            let Some(v) = guard.as_mut() else { return };
            let Ok(Some(mut g)) = v.store().get_group(&id) else { return };
            if g.name == name.as_str() {
                return;
            }
            g.name = name.to_string();
            g.updated_at = now_millis();
            if let Err(e) = v.upsert_group(&g) {
                eprintln!("could not rename the group: {e}");
                return;
            }
            refresh_list(v, &ctx.model, &ctx.collapsed.borrow());
        });
    }
    {
        let ctx = ctx.clone();
        list.on_move_row(move |src, dst| {
            touch(&ctx);
            move_row(&ctx, src, dst);
        });
    }

    // ---- Recolouring a row (folder or memo) from the list. ----
    {
        let ctx = ctx.clone();
        list.on_set_row_color(move |id, is_group, color| {
            touch(&ctx);
            list::set_row_color(&ctx, &id, is_group, &color);
        });
    }

    // ---- Device linking (pairing, shared devices) is wired up by the pairing module. ----
    let _pairing = pairing::wire(&lock, &list, &syncthing, lan.clone(), my_device_id.clone(), &vault_dir);

    // ---- Periodic merge, pulling other devices' logs into the list and stickies. ----
    // The interval is a setting, so saving settings re-arms the timer; hence the Rc.
    let merge_timer = Rc::new(slint::Timer::default());
    start_merge_timer(&merge_timer, &ctx, list.as_weak());

    // The tray is created further down, but the settings callback needs its handle to
    // relabel the menu on a language change, so the slot is prepared here.
    let tray_handle: Rc<RefCell<Option<tray::TrayHandle>>> = Rc::new(RefCell::new(None));

    // ---- Settings window ----
    {
        let ctx = ctx.clone();
        let win = settings_win.as_weak();
        let unlocked = unlocked.clone();
        list.on_open_settings(move || {
            touch(&ctx);
            let Some(w) = win.upgrade() else { return };
            fill_settings_window(&ctx, &w);
            w.set_unlocked(unlocked.get());
            w.set_status(SharedString::new());
            present(&w);
        });
    }
    {
        let win = settings_win.as_weak();
        settings_win.on_close_requested(move || {
            if let Some(w) = win.upgrade() {
                let _ = w.hide();
            }
        });
    }
    {
        let ctx = ctx.clone();
        let win = settings_win.as_weak();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let merge_timer = merge_timer.clone();
        let tray_handle = tray_handle.clone();
        let security_weak = security_win.as_weak();
        let history_weak = history_win.as_weak();
        settings_win.on_apply(move || {
            let Some(w) = win.upgrade() else { return };
            let (Some(lock), Some(list)) = (lock_weak.upgrade(), list_weak.upgrade()) else {
                return;
            };
            touch(&ctx);

            let mut next = Settings {
                lang: w.get_lang_sel().to_string(),
                unlock_days: w.get_unlock_days(),
                idle_lock_minutes: w.get_idle_minutes(),
                default_color: w.get_default_color().to_string(),
                default_opacity: w.get_default_opacity(),
                merge_seconds: w.get_merge_seconds(),
                update_check: w.get_update_check(),
                // Not a user-visible field: keep whatever the last check recorded, so saving
                // settings does not silently schedule another request.
                last_update_check: ctx.settings.borrow().last_update_check,
            };
            next.sanitize();
            let prev_unlock_days = ctx.settings.borrow().unlock_days;
            next.save(&ctx.dir);
            *ctx.settings.borrow_mut() = next.clone();

            // Write the sanitized values back, so out-of-range input never changes silently.
            fill_settings_window(&ctx, &w);
            apply_lang(&ctx, &lock, &list, &w, &security_weak.unwrap(), &history_weak.unwrap());
            if let Some(t) = tray_handle.borrow().as_ref() {
                t.refresh();
            }
            start_merge_timer(&merge_timer, &ctx, list.as_weak());

            // Shortening or disabling the stay-unlocked window leaves an existing session in
            // violation of it, so drop the session and ask for the password next time.
            let status = if next.unlock_days != prev_unlock_days {
                settings::clear_session(&ctx.dir);
                t!("msg.settings_saved_relock")
            } else {
                t!("msg.settings_saved")
            };
            w.set_status(SharedString::from(status));
        });
    }
    {
        let ctx = ctx.clone();
        let win = settings_win.as_weak();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let unlocked = unlocked.clone();
        settings_win.on_lock_now(move || {
            let (Some(lock), Some(list)) = (lock_weak.upgrade(), list_weak.upgrade()) else {
                return;
            };
            lock_now(&ctx, &lock, &list, &unlocked);
            if let Some(w) = win.upgrade() {
                w.set_unlocked(false);
                let _ = w.hide();
            }
        });
    }
    {
        let ctx = ctx.clone();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let unlocked = unlocked.clone();
        list.on_lock_now(move || {
            let (Some(lock), Some(list)) = (lock_weak.upgrade(), list_weak.upgrade()) else {
                return;
            };
            lock_now(&ctx, &lock, &list, &unlocked);
        });
    }

    // ---- Idle auto-lock ----
    let idle_timer = slint::Timer::default();
    {
        let ctx = ctx.clone();
        let lock_weak = lock.as_weak();
        let list_weak = list.as_weak();
        let unlocked = unlocked.clone();
        idle_timer.start(TimerMode::Repeated, IDLE_CHECK_INTERVAL, move || {
            let minutes = ctx.settings.borrow().idle_lock_minutes;
            if minutes <= 0 || !unlocked.get() {
                return;
            }
            if ctx.last_activity.get().elapsed() < Duration::from_secs(minutes as u64 * 60) {
                return;
            }
            let (Some(lock), Some(list)) = (lock_weak.upgrade(), list_weak.upgrade()) else {
                return;
            };
            lock_now(&ctx, &lock, &list, &unlocked);
        });
    }

    // ---- Magnetic snapping: a sticky that stops moving clips to the screen or another
    // sticky's edge. Works where window positions are readable (X11), inert on Wayland. ----
    let snap_timer = slint::Timer::default();
    {
        let stickies = ctx.stickies.clone();
        snap_timer.start(TimerMode::Repeated, SNAP_INTERVAL, move || snap_tick(&stickies));
    }

    // ---- Tray icon ----
    APP.with(|a| {
        *a.borrow_mut() = Some(AppUi {
            lock: lock.clone_strong(),
            list: list.clone_strong(),
            history: history_win.clone_strong(),
            history_subject: history_subject.clone(),
            settings: settings_win.clone_strong(),
            unlocked: unlocked.clone(),
            ctx: ctx.clone(),
        })
    });
    // The tray lives as long as this handle, which lives to the end of main.
    *tray_handle.borrow_mut() = Some(tray::start());

    // Window icons only apply once the event loop has created the winit windows: a one-shot
    // timer covers the lock and list windows, and later windows get theirs where they are
    // shown (open_sticky, the tray toggle).
    let icon_timer = slint::Timer::default();
    {
        let lock_w = lock.as_weak();
        let list_w = list.as_weak();
        icon_timer.start(TimerMode::SingleShot, Duration::from_millis(100), move || {
            if let Some(w) = lock_w.upgrade() {
                set_window_icon(w.window());
            }
            if let Some(w) = list_w.upgrade() {
                set_window_icon(w.window());
            }
        });
    }

    // ---- Update check ----
    // Once a day at most, and only if the user has left it on. Silent unless it finds
    // something: an offline machine should not be told about its own network.
    if ctx.settings.borrow().update_check_due() {
        update::spawn_check(&ctx, false);
    }
    {
        let ctx = ctx.clone();
        // The button asks regardless of the daily gap, and says what came back.
        settings_win.on_check_update(move || update::spawn_check(&ctx, true));
    }
    settings_win.on_open_update(update::open_release_page);
    list.on_open_update(update::open_release_page);

    // Do not raise the lock window when the session already unlocked us.
    if !auto_unlocked {
        present(&lock);
    }
    slint::run_event_loop_until_quit()?;

    // Shut the daemon down explicitly. Waiting for `Syncthing`'s `Drop` would not do: window
    // callbacks (and the thread-local `APP`) hold their own `Rc` clones of this and outlive
    // `main`, so on exit the daemon would be killed by the OS instead — a safety net meant
    // for crashes, not for the ordinary way of quitting.
    if let Some(st) = syncthing.borrow_mut().take() {
        if let Err(e) = st.shutdown() {
            eprintln!("the sync daemon did not shut down cleanly: {e}");
        }
    }
    Ok(())
}
