// Windows release builds run as a GUI subsystem app: without this a cmd window opens
// alongside, and closing it kills the app. Debug builds keep the console for println.
#![cfg_attr(all(windows, not(debug_assertions)), windows_subsystem = "windows")]
//! Ymemo desktop app (Slint): a tray-resident sticky-note app.
//!
//! Windows:
//!  - `LockWindow` — master password on startup, opening or creating the vault.
//!  - `ListWindow` — the memo list, toggled from the tray icon.
//!  - `StickyWindow` — one frameless window per memo. The body is the editor (debounced
//!    autosave), the title bar drags it around, a double click folds it to a thin bar,
//!    + adds a memo and x closes the window without deleting anything.
//!
//! Closing every window leaves the app in the tray (`run_event_loop_until_quit`); only the
//! tray menu quits.

use std::cell::{Cell, RefCell};
use std::rc::Rc;

use anyhow::Result;
use slint::{ComponentHandle, ModelRc};
use ymemo_core::{diag, sync::Syncthing, vault::Vault};

slint::include_modules!();

// `apply_strings`, generated by build.rs from the i18n catalog.
include!(concat!(env!("OUT_DIR"), "/i18n_apply.rs"));

mod autostart;
mod hangul;
mod highlight;
mod history;
mod icon;
mod instance;
mod list;
mod lock;
mod markdown;
mod pairing;
mod screens;
mod security;
mod session;
mod settings;
mod settings_window;
mod startup;
mod state;
mod sticky;
mod sync;
mod timers;
mod tray;
mod update;
mod window;

use state::{AppUi, Ctx, Ui, APP};
use sync::{start_merge_timer, start_syncthing};

fn main() -> Result<()> {
    startup::prefer_x11();
    let dir = startup::data_dir();
    if let Some(result) = startup::run_command(&dir) {
        return result;
    }

    // Only one instance per user: a second one would run a second sync daemon over the same
    // syncthing home and write the same cache. It happens easily enough — the Windows
    // installer's startup task plus a click on the icon of an app that lives in the tray.
    // From here on this is a real session, so the directory has to exist.
    let _ = std::fs::create_dir_all(&dir);

    // From here on, everything that reports a failure also reaches <data_dir>/ymemo.log. A
    // release build has `windows_subsystem = "windows"` and so no console at all, which is
    // exactly the platform a bug report is most likely to come from.
    ymemo_core::diag::init(&dir);
    diag!("--- ymemo {} starting on {} ---", env!("CARGO_PKG_VERSION"), std::env::consts::OS);

    let Some(_instance) = instance::acquire(&dir) else {
        instance::send_show(&dir); // hand the running one the foreground instead
        diag!("Ymemo is already running; asked it to show itself");
        return Ok(());
    };
    instance::serve(&dir);

    startup::select_renderer();

    // The settings, security, history and approval windows are built once and only shown or
    // hidden; rebuilding them would reset their position every time. The approval window has
    // to be able to appear while every other window is closed, since the app otherwise lives
    // in the tray.
    let ui = Ui {
        lock: LockWindow::new()?,
        list: ListWindow::new()?,
        settings: SettingsWindow::new()?,
        security: SecurityWindow::new()?,
        history: HistoryWindow::new()?,
        approve: ApproveWindow::new()?,
    };

    let min_password = ymemo_core::crypto::MIN_PASSWORD_CHARS as i32;
    ui.lock.set_min_password(min_password);
    ui.security.set_min_password(min_password);

    // Syncthing starts before unlocking (it needs no key), so a new device can pair first,
    // receive vault.json and the logs, and only then be asked for the password.
    let vault_dir = dir.join("vault");
    let _ = std::fs::create_dir_all(&vault_dir);
    let st = start_syncthing(&dir, &vault_dir);
    let my_device_id = st.as_ref().and_then(|st| pairing::show_own_code(st, &ui.lock, &ui.list));
    // Dropping this on exit shuts the daemon down.
    let syncthing: Rc<RefCell<Option<Syncthing>>> = Rc::new(RefCell::new(st));
    let lan = pairing::start_lan(my_device_id.as_ref());

    let ctx = Ctx::new(dir.clone(), startup::load_settings(&dir, &syncthing), syncthing.clone());
    ui.list.set_rows(ModelRc::from(ctx.model.clone()));
    ui.list.set_folder_choices(list::folder_choices());
    let unlocked = Rc::new(Cell::new(false));

    settings_window::apply_lang(
        &ctx,
        &ui.lock,
        &ui.list,
        &ui.settings,
        &ui.security,
        &ui.history,
        &ui.approve,
    );
    security::wire(&ctx, &ui.settings, &ui.security);

    // Past versions of a memo or folder.
    let history_subject: history::Subject = Rc::new(RefCell::new(None));
    history::wire(&ctx, &ui.history, &history_subject);
    history::wire_list(&ctx, &ui.list, &ui.history, &history_subject);

    // First run? A vault.json means an existing vault (unlock); without one this is a new
    // device (create, or link to an existing one). Without the distinction a new device
    // would create a vault with its own salt before pairing delivers vault.json, and the
    // keys would diverge.
    let vault_exists = vault_dir.join("vault.json").exists();
    ui.lock.set_vault_exists(vault_exists);
    ui.lock.set_has_recovery(ymemo_core::vault::recovery_code_exists(&vault_dir));

    // A vault created on this device waits here while its recovery code is on screen: it is
    // opened only once the user confirms they wrote the code down.
    let pending_vault: Rc<RefCell<Option<Vault>>> = Rc::new(RefCell::new(None));
    let auto_unlocked = vault_exists && lock::unlock_from_session(&ctx, &ui, &unlocked, &vault_dir);
    // Whether the vault on disk was made on this device. The watcher in `pairing` uses it to
    // tell a header that arrived over sync from one this device just wrote itself.
    let created_here: Rc<Cell<bool>> = Rc::new(Cell::new(false));

    lock::wire(&ctx, &ui, &unlocked, &syncthing, &pending_vault, &created_here);
    list::actions::wire(&ctx, &ui, &unlocked);

    // Device linking (pairing, shared devices) is wired up by the pairing module.
    let _pairing = pairing::wire(
        &ui.lock,
        &ui.list,
        &ui.approve,
        &syncthing,
        lan.clone(),
        my_device_id.clone(),
        pairing::VaultOrigin { dir: &vault_dir, created_here: created_here.clone() },
    );

    // Periodic merge, pulling other devices' logs into the list and stickies. The interval
    // is a setting, so saving settings re-arms the timer; hence the Rc.
    let merge_timer = Rc::new(slint::Timer::default());
    start_merge_timer(&merge_timer, &ctx, ui.list.as_weak());

    // The tray is created further down, but the settings callback needs its handle to
    // relabel the menu on a language change, so the slot is prepared here.
    let tray_handle: Rc<RefCell<Option<tray::TrayHandle>>> = Rc::new(RefCell::new(None));
    settings_window::wire(&ctx, &ui, &unlocked, &syncthing, &merge_timer, &tray_handle);

    let _timers = timers::start(&ctx, &ui, &unlocked);

    APP.with(|a| {
        *a.borrow_mut() = Some(AppUi {
            lock: ui.lock.clone_strong(),
            list: ui.list.clone_strong(),
            history: ui.history.clone_strong(),
            history_subject: history_subject.clone(),
            settings: ui.settings.clone_strong(),
            unlocked: unlocked.clone(),
            ctx: ctx.clone(),
        })
    });
    // The tray lives as long as this handle, which lives to the end of main.
    {
        let tray = tray::start();
        // The stickies leave the taskbar only if there is somewhere else to reach them from.
        ctx.has_tray.set(tray.is_available());
        if !tray.is_available() {
            diag!("no tray on this desktop; the notes keep their taskbar buttons");
        }
        // The desk is often already on screen by now: a valid session opens the vault — and
        // with it every note that was left out — well before this point. See the function.
        sticky::hide_open_notes_from_taskbar(&ctx);
        // A quiet start needs somewhere to be quiet *in*. With no tray there is no icon to
        // click, so the app would sit invisible holding an unlocked vault — show it instead.
        if ctx.quiet_start.get() && !ctx.has_tray.get() {
            lock::show_desk(&ctx, &ui.list.as_weak());
        }
        *tray_handle.borrow_mut() = Some(tray);
    }

    // Update check: once a day at most, and only if the user has left it on. Silent unless
    // it finds something: an offline machine should not be told about its own network.
    if ctx.settings.borrow().update_check_due() {
        update::spawn_check(&ctx, false);
    }

    // Started by the session rather than by the user: come up in the tray and leave the
    // screen alone. **Only where a tray actually registered** — on a desktop with none
    // (vanilla GNOME, and the reason `Ctx::has_tray` exists) a hidden start would be an app
    // with no window and no icon, running an unlocked-vault timer nobody can reach.
    let stay_hidden = autostart::launched_hidden() && ctx.has_tray.get();
    // Do not raise the lock window when the session already unlocked us.
    if !auto_unlocked && !stay_hidden {
        // `resize` only fires on a *change*, and the panel a fresh window opens on has not
        // changed into anything — which is how a new device met the first-run choice with its
        // second card cut off by the bottom edge.
        ui.lock.invoke_apply_size();
        crate::window::present_centered(&ui.lock, None);
    }
    slint::run_event_loop_until_quit()?;

    // Shut the daemon down explicitly. Waiting for `Syncthing`'s `Drop` would not do: window
    // callbacks (and the thread-local `APP`) hold their own `Rc` clones of this and outlive
    // `main`, so on exit the daemon would be killed by the OS instead — a safety net meant
    // for crashes, not for the ordinary way of quitting.
    if let Some(st) = syncthing.borrow_mut().take() {
        if let Err(e) = st.shutdown() {
            diag!("the sync daemon did not shut down cleanly: {e}");
        }
    }
    Ok(())
}
